### ISSUE TITLE
[BUG] Can't change settings to the documents

### ISSUE THREAD

**Issue by alkalle** [astubenbord/paperless-mobile#111]
**Describe the bug**
Hi astubenbord,
thanks for that really good additional App for paperless-ngx. It saves me much time.
I think since the last update to 2.0.5+22 I can not use the buttons in the detailed view of one document (I dont know exactly when my smartphone did the update). The buttons for download, preview etc. dont works. The edit button is additionaly not visible. I hope the picture below clearifice my description.
But it is possible to slide between the different types like overview, content, meta-data.

Did you have a solution? I can test the Version before if it is necessary.

best regards
alkalle

**To Reproduce**
1. Go in the App
2. Click open one document in the detailed view
3. click on the buttons they not work

**Expected behavior**
If i click on the buttons, the menu behind have to open, the file is deleted or the download has to start.

**Screenshots**
The Button in the left red box don't work. The button in the right box isnt available.

![Screenshot_2023-02-16-16-45-06-690_de astubenbord paperless_mobile](https://user-images.githubusercontent.com/110219064/219419684-c177d35b-224d-4ae8-9fdb-d97ee33bcff1.jpg)

**Device Information:**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 11
 - 2.0.5+22
 - 1.12.2

**Comment by alkalle** [comment]
I have downloaded the App from the Play Store, additionally.

**Comment by astubenbord** [comment]
Hi, the buttons are only greyed out when your device is not connected to the internet. I can see from your status bar that you appear to have a VPN running, this might be related to the last bullet point in #104 

Do you have a way to check whether it works with the VPN turned off?

**Comment by astubenbord** [comment]
Aah yes, I see. I currently consider the device connected to the internet if there is either a wifi, mobile or ethernet connection. There is however also an option for VPN, which I did not consider. Will fix and update the app!

**Comment by alkalle** [comment]
Thanks for repairing the bug. I've tested it sunday and now it works.
