### ISSUE TITLE
[BUG] Access over VPN is restricted

### ISSUE THREAD

**Issue by Kh3nsu** [astubenbord/paperless-mobile#117]
**Describe the bug**
When I'm not home I access my local network over WIreGuard.
I noticed a problem when trying to view, edit delete etc. any document in Paperless, but only in the Paperless-mobile
app. I can directly access paperless over the browser and can do all the stuff there. My WireGuard connection has no
rule to prevent any traffic going into my network and as everything else works like HomeAssistant, PhotoPrism and also 
direct access to paperless-ngx over a normal browser it has to be a bug with the app.
The edit, view, download, delete, share button does work when I'm in my local network.

Paperless-ngx is only accessible over HAProxy.

**To Reproduce**
1. Connect to Network over WireGuard
2. Open Paperless-Mobile
3. Open any Document
4. Buttons are greyed out and not pushable

**Expected behavior**
Able to view, edit delete etc. documents when accessing paperless over wireguard with the app.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Device Information:**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android 13
 - Paperless Mobile version: 2.0.5+22
 - Paperless Server version 1.12.2

**Comment by astubenbord** [comment]
Hi, thanks for taking the time to create an issue. This was already fixed in #112 and I will update the app the next days.

Cheers

**Comment by Kh3nsu** [comment]
Sorry I must have overlooked while skimming!
Thank you :)

**Comment by astubenbord** [comment]
Does it work now with 2.0.6?

**Comment by Kh3nsu** [comment]
Yes ;)
