### ISSUE TITLE
Sharing. Pdf missing

### ISSUE THREAD

**Issue by schlumpfteam** [astubenbord/paperless-mobile#119]
While one can chose between "original" and "PDF" for downloading, one can Only send the original document in the "sharing" process. IT would bei great if you also could chose between original and PDF.
Thank you Gunnar

**Comment by astubenbord** [comment]
Hi, what would be the use case for that? Paperless converts your files to PDF during the consumption process. This only makes sense if you upload a multi-paged document imo, which is already automatically converted to PDF by the app.
