### ISSUE TITLE
My app is suddenly in the Polish language 

### ISSUE THREAD

**Issue by zjean** [astubenbord/paperless-mobile#121]
Or a language that looks like it.
How can I restore to English?

**Comment by astubenbord** [comment]
That's weird. Was it just set to polish one day you opened the app? Maybe after the recent update?

Anyway, you can open the app drawer (three bars on the left of the search bar), navigate to application (first option) , then language (again first option).

Hope this helps.

**Comment by zjean** [comment]
Thanks for your quick response.
I think it happened after the latest update, but are not sure.
It looks like the setting screen is not working or empty:

![Screenshot_20230223-211122_Paperless_Mobile.png](https://user-images.githubusercontent.com/441924/221019521-d81555c2-f377-488c-b4bb-9858f98535bd.png)

![Screenshot_20230223-211138_Paperless_Mobile.png](https://user-images.githubusercontent.com/441924/221019522-5e6def3e-9a83-41a9-b7bb-257774aa7cf0.png)

![Screenshot_20230223-211114_Paperless_Mobile.png](https://user-images.githubusercontent.com/441924/221019520-48100d1d-e8f5-47f7-b754-52344d592c69.png)

**Comment by astubenbord** [comment]
Oh, okay. I'll have a look.

**Comment by astubenbord** [comment]
What's your system language?

**Comment by zjean** [comment]
Dutch. I cleared the app data, and now it is English again, as expected

**Comment by astubenbord** [comment]
Okay good, still weird that it just switched, I don't know how that could happen :/

**Comment by astubenbord** [comment]
You can check if 2.0.7 resolves this.
