### ISSUE TITLE
[BUG] Dropdown options for categories is not selectable/clickable

### ISSUE THREAD

**Issue by agichim** [astubenbord/paperless-mobile#132]
**Describe the bug**
When clicking the different categories (e.g., Correspondant, Document Type) to open the dropdown and select an option the dropdown with the options is not clickable and simply stays open. If the option you need to select is on top of the "Date" the date gets clicked.

**To Reproduce**
1. Go to editing a document
2. Click on Correspondant and select an option

**Expected behavior**
The option from each dropdown of each category should be selected.

**Screenshots**
https://user-images.githubusercontent.com/51931067/222812439-42ab9d21-e969-42f1-8a2a-1f4e0160e432.mp4

**Device Information:**
 - Device: [e.g. Motorola Moto G8 Power]
 - OS: [e.g. Android 11]
 - Paperless Mobile version [e.g. 2.0.9+26, see in 'About this app' in drawer]
 - Paperless Server version [e.g. 1.11.3 (API v2, see in drawer header]

**Additional context**

**Comment by astubenbord** [comment]
Hi, this is a known issue, see the troubleshooting section in the Readme.

**Comment by agichim** [comment]
I had to disable accessibility for all apps that used it. So in a way, this is still a bug, right? Is there a different workaround? Still, I'm using Bitwarden more than I use Paperless on Android to edit files.

**Comment by astubenbord** [comment]
Hm on Android 11 you don't need accessibility features to use the bitwarden auto fill I guess, I didn't need it for Android 10. Accessibility is only required on older devices I think.

**Comment by agichim** [comment]
Oh, I will have a look then.

**Comment by CaffeinatedTech** [comment]
Could you open this back up please.  We need a proper fix to this bug.  Disabling features of other apps can't be the solution.  You can use bitwarden without the draw-over feature sure, but the keyboard quick-action is unreliable, or you have to slide to find bitwarden in the list.  Also, I can't recall another app with this same issue, expecting people to disable accessibility features.

It seems like the popover list is using the wrong z index, or it needs to prevent the click event from bubbling up.

**Comment by astubenbord** [comment]
@CaffeinatedTech Okay, so it turns out that the drop down menus are not flexible enough to achieve what I'm currently trying to do, so the form fields will be updated in the next version.
The plan is to open a full page search for correspondents etc. When tapping on the field. What's your take on this approach? I'd like to get some feedback from users (like you).

Cheers
