### ISSUE TITLE
[BUG] Android 12 Samsung Galaxy S20+ Edits are not saved/popups can't be selected 

### ISSUE THREAD

**Issue by Kani3D** [astubenbord/paperless-mobile#138]
**Describe the bug**
Edits on documents are not saved. (I.e. adding a correspondent)
Suggestions of correspondents can't be selected.
I see them but if I click on it it will only select the background instead of the popup.

**Device Information:**
 - Device: [e.g. Samsung Galaxy S20+]
 - OS: [e.g. Android 12]
 - Paperless Mobile version [latest]
 - Paperless ngx Server version

**Comment by astubenbord** [comment]
Hi, can you please check the troubleshooting section in the Readme? This has been reported many times, see #83 for a more detailed discussion.

Cheers!

**Comment by astubenbord** [comment]
And regarding the saves, do you get an error?
