### ISSUE TITLE
[BUG] Cannot login with NGINX basic auth 

### ISSUE THREAD

**Issue by astubenbord** [astubenbord/paperless-mobile#139]
Add Basic auth to server connection page

**Comment by JigSawFr** [comment]
Hum, not better to whitelist api on user side for auth? As it's not related to paperless

**Comment by astubenbord** [comment]
Sure, I created this issue because someone asked for it, but I think it doesn't make much sense to have both basic auth and API login enabled at the same time (which isn't possible anyway since we have to send both authorization headers for paperless and the basic auth at the same time)

**Comment by mikegleasonjr** [comment]
You can specify multiple values for an Authorization header, we would have to check if the web servers and the API works and are implemented correctly according to the RFC: https://stackoverflow.com/a/38515091

**Comment by astubenbord** [comment]
@mikegleasonjr It does not seem like there is a consensus on whether this is defined or not. The referenced RFC does not make a statement about this case, at least from what I've read. I'm sure the paperless API is implemented according to these standards since it builds on Django, which I _assume_ to be conforming. Have you already tried to make a request using curl or postman or whatever to see if you can authenticate using this method? If this is not possible, then you'd have to ask the paperless team to add support for this kind of scenario. I think I have already tried this a while back and was not successful, but maybe I didn't do it correctly so who knows.

**Comment by mikegleasonjr** [comment]
> @mikegleasonjr It does not seem like there is a consensus on whether this is defined or not.

I agree. Go doesn't support it, see https://github.com/astubenbord/paperless-mobile/issues/154#issuecomment-1860342366
