### ISSUE TITLE
[Feature] Upload support for files

### ISSUE THREAD

**Issue by yahooooza** [astubenbord/paperless-mobile#14]
The scanner feature works great (tested on One Plus 8T). Sometimes i want to upload a file i already have (.pdf, .jpeg). I tried to use my filemanager instead of the camera, but that didn't worked. Maybe a new button to upload local documents would be nice. That is also pretty easy in flutter.

Even better would be a support for the sharing function in Android to directly upload a document without opening the app in the first place.

Maybe i will implement that in a seperat branch if i have time in the weekend. I will report.

I appreciate your work. Very good designed.

**Comment by astubenbord** [comment]
Thanks for the idea, so you just want a button to upload a single document without modifying it (e.g. add pages to the document)?

**Comment by yahooooza** [comment]
It would be sufficient in the first place to only upload documents without modifying it. I think there are already good solution to modify documents out there. But a function to export the result from that app to the paperless-mobile app would be great, so you doesn't have to save the document, open the app and upload it.

Here is a good plugin for flutter for that:
https://pub.dev/packages/receive_sharing_intent

Cheers

**Comment by astubenbord** [comment]
Thanks for the great input, I implemented the file picking and uploading. The way I currently have it is that the image is directly converted to a pdf file in the app and uploaded via the upload dialog. This way the complexity stays low as I don't have to pass around mime types. Paperless does this conversion anyway. I'll look into the receive_sharing_intent.

Cheers!

**Comment by astubenbord** [comment]
@yahooooza Implemented in the newest release (https://github.com/astubenbord/paperless-mobile/releases/tag/v1.0.4-beta). Feel free to give me feedback if it works for you so I can close this issue.
