### ISSUE TITLE
Support a paperless instance behind basic auth 

### ISSUE THREAD

**Issue by mikegleasonjr** [astubenbord/paperless-mobile#154]
I am securing my public instance behind basic auth, can we support that?

Thanks

**Comment by astubenbord** [comment]
Hi, this has already been discussed in #139.

Unfortunately, the authorization headers of both proxy for basic auth and paperless for API auth collide, therefore this cannot be implemented. I would also highly recommend to use client certificates which are far more secure than basic auth (which doesn't really add any security anyway as the API itself is already secured with your credentials).

**Comment by gregbtm** [comment]
Same issue here. Where do I even get a client cert file? The button doesn't work at all to connect without it.

**Comment by mikegleasonjr** [comment]
I ended up using basic auth and not using this app. I use syncthing to have a paperless consume folder on my devices. And I use the browser to go to the website directly.

**Comment by mikegleasonjr** [comment]
You can specify multiple values for an Authorization header, we would have to check if the web servers and the API works and are implemented correctly according to the RFC: https://stackoverflow.com/a/38515091

**Comment by astubenbord** [comment]
> Same issue here. Where do I even get a client cert file? The button doesn't work at all to connect without it.

I understand that the "new" login form is not that intuitive as it requires the user to press the done button on the keyboard. I'm working on an improved version at the moment. 
You don't need client certificates to use the app. However, when exposing services to the internet I think it offers greater levels of security (correct me if I'm wrong) than basic auth. 

Maybe raise this request with the paperless-ngx team if you want multiple authorization tokens to be accepted.

**Comment by mikegleasonjr** [comment]
Orrrrr... Support tokens for authentication as well as basic auth.

As per the [documentation](https://docs.paperless-ngx.com/api/#authorization):

----------

### Authorization
The REST api provides three different forms of authentication.

## Basic authentication

Authorize by providing a HTTP header in the form

`Authorization: Basic <credentials>`

where credentials is a base64-encoded string of `<username>:<password>`

## Session authentication

When you're logged into paperless in your browser, you're automatically logged into the API as well and don't need to provide any authorization headers.

## Token authentication

You can create (or re-create) an API token by opening the "My Profile" link in the user dropdown found in the web UI and clicking the circular arrow button.

Paperless also offers an endpoint to acquire authentication tokens.

POST a username and password as a form or json string to /api/token/ and paperless will respond with a token, if the login data is correct. This token can be used to authenticate other requests with the following HTTP header:

`Authorization: Token <token>`

Tokens can also be managed in the Django admin.

----------

The point of discussing if a technology is secure or not is irrelevant. The HTTP protocols has several standards, we just ask if you can support them 🙏🏻 

If you have a patreon or a support link, I can participate if you want the tokens implemented!

Thanks for your efforts for this app.

**Comment by astubenbord** [comment]
Okay, just so we're on the same page: You're essentially asking me to allow users to specify both the basic auth header for e.g. your proxy (through an additional setting on the login page) and the token auth header for paperless? Or is there something I'm missing?
Something like this: `Authorization: Bearer mF_9.B5f-4.1JqM, Basic YXNkZnNhZGZzYWRmOlZLdDVOMVhk`?

Out of interest: How does paperless/django know which token to use since it allows both token and basic auth?

**Comment by mikegleasonjr** [comment]
I think we can forget my idea, Go doesn't support setting/getting multiple `Authorization` headers like a list in your example. It will override the whole header on set, or try to parse the whole header as a single thing on parse:

- https://github.com/traefik/traefik/blob/master/pkg/middlewares/auth/basic_auth.go#L65
- https://go.dev/src/net/http/request.go#L948
