### ISSUE TITLE
build process fails because of missing signingConfigs for release version

### ISSUE THREAD

**Issue by yahooooza** [astubenbord/paperless-mobile#16]
The are several solutions to this problem. The easiest is to note in the README that in order to compile the code it is neccessary to change in android/app/build.gradle from

```
buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }
```
to

```
buildTypes {
       release {
           signingConfig signingConfigs.debug
       }
   }
```

Clearly it is possible to compile in Debug mode. But then you give up a lot of performance optimization.

Cheers

**Comment by astubenbord** [comment]
Thanks for the hint, I'll add it to the readme!
