### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dannytsang** [astubenbord/paperless-mobile#162]
**Describe the bug**
Trying to add labels is very hard. It seems to register the tap on the form rather than the list of labels.

**To Reproduce**
1. Go to a document.
2. Edit the document using the pencil ✏️
3. Start typing into the label field of an existing label that has not been added to the document.
4. Tap a label in the list.

**Expected behavior**
The label should be added to the document, however, it selects the document field underneath e.g. Storage path, Correspondence.

**Screenshots**
I had to cropt and cut the video to make it below the max file size limit but I hope this helps illustrate the issue.
https://user-images.githubusercontent.com/567982/236617681-3fc9cdf3-a1ba-4a62-a72d-86d4fec91d98.mp4

**Device Information:**
 - Device: Pixel 7 pro
 - OS: Android 13
 - Paperless Mobile version 2.1.0+27
 - Paperless Server version 1.14.4

**Additional context**

**Comment by astubenbord** [comment]
Hi, this issue is known and there is an open beta on Google Play with reworked label forms and support for multiple users. You have to go to the official store page of Paperless Mobile on google play and join the open beta there. You should then be able to update to 2.2.0+28.

**Comment by dannytsang** [comment]
Tested in +28 and much better. Thank you @astubenbord

**Comment by astubenbord** [comment]
Np, glad it works :)
