### ISSUE TITLE
[BUG] Upload with in app Scanfunction fails

### ISSUE THREAD

**Issue by Latschenharry** [astubenbord/paperless-mobile#164]
**Describe the bug**
When creating a scan with the in App scanner and trying to upload it. The App returns an unkown error

**To Reproduce**
1. Go to 'Scanner'
2. Click on 'Upload'
3. Error Appears

**Expected behavior**
Scan gets uploaded sucessfully to the paperless server

**Screenshots**
![Screenshot_2023-05-09-10-45-14-89_d0490b14dafa2e72046a4566e3d7d027](https://user-images.githubusercontent.com/12736979/237044908-2bd679be-5801-45e2-8d3c-d12ff56db1d6.jpg)

**Device Information:**
 - Device: OnePlus 9 Pro
 - OS: Android 13
 - Paperless Mobile version 2.2.4+32
 - Paperless Server version 1.14.4 (API v3)

**Additional context**
Docker Webserver Logs show no error

**Comment by astubenbord** [comment]
Hi, this is expected behavior as the app has not yet been adapted to the new API (V3) that came with 1.14.1. 
I'm working on it but it will take some time as there are quite a lot of things to consider.
