### ISSUE TITLE
Add a new view results in blank screen

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#168]
When clicking on the 'plus' button for adding a new view, then just a blank screen is shown. I'm using the latest beta from google play and paperless-ngx 1.13.0

**Comment by astubenbord** [comment]
Fixed in https://github.com/astubenbord/paperless-mobile/releases/tag/v2.2.5.

**Comment by astubenbord** [comment]
Please always perform a fresh install for new beta versions. I don't have the time to write migration scripts between versions and I don't want to clear the data on first startup as new updates don't necessarily include breaking changes. The models are still changing, but it will eventually get stable and allow seamless updates as expected.
