### ISSUE TITLE
[BUG] Login error after update 2.2.5

### ISSUE THREAD

**Issue by Latschenharry** [astubenbord/paperless-mobile#171]
**Describe the bug**
After clocking login a huge error appears

**To Reproduce**
1. Go to 'app'
2. Enter paperless url
3. enter login credentials
4. press login

**Expected behavior**
Login is successfull

**Screenshots**
![Screenshot_2023-05-12-14-39-40-86_d0490b14dafa2e72046a4566e3d7d027](https://github.com/astubenbord/paperless-mobile/assets/12736979/8da91012-2b8c-4712-a4a0-6d2eb8845813)

Device Information:

Device: OnePlus 9 Pro
OS: Android 13
Paperless Mobile version 2.2.5
Paperless Server version 1.14.4 (API v3)

**Comment by Latschenharry** [comment]
Clearing cache and reinstalling the app doesnt help.

**Comment by astubenbord** [comment]
Ah, seems like they added permissions in 1.14.4. I'll update that. Sorry for the inconvenience.

**Comment by astubenbord** [comment]
Update is on the way
