### ISSUE TITLE
Have to clear Cache and Data after installing v2.2.6

### ISSUE THREAD

**Issue by reichelper** [astubenbord/paperless-mobile#172]
I have had the same problem just now. 
Clear the Data an the Cache solved the problem and an could login normally.

_Originally posted by @steinm in https://github.com/astubenbord/paperless-mobile/issues/168#issuecomment-1545974157_

**Comment by astubenbord** [comment]
See https://github.com/astubenbord/paperless-mobile/issues/168#issuecomment-1545991168
