### ISSUE TITLE
[BUG] flutter_localizations intl version compatibility

### ISSUE THREAD

**Issue by losiu97** [astubenbord/paperless-mobile#173]
**Describe the bug**
This is what happened when i tried to install the project
```
*****@***** paperless-mobile % flutter packages pub get
Resolving dependencies... (9.2s)
Because paperless_mobile depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because paperless_mobile depends on intl ^0.17.0, version solving failed.
```

**To Reproduce**
Install fresh flutter sdk. Run flutter packages pub get in the project root

**Expected behavior**
The packages to be installed

**Device Information:**
 - Flutter SDK 3.1.0

**Comment by losiu97** [comment]
I will create a PR with a fix

**Comment by astubenbord** [comment]
This should already be resolved on the 1.14-permissions branch.

**Comment by losiu97** [comment]
Ah sorry, did not know that was the dev branch

**Comment by astubenbord** [comment]
It technically isn't, you were right by pulling the development branch. I just currently do most changes on this branch to implement the changes that came with paperless-ngx 1.14+ since it required a major refactoring.
