### ISSUE TITLE
[BUG] Cant open documents when searched

### ISSUE THREAD

**Issue by Latschenharry** [astubenbord/paperless-mobile#175]
**Describe the bug**
When searching for a document. The screen stays grey when i try to open it,

**To Reproduce**
1. Click the search bar
2. type any keyword
3. Clicking a Document
4. App window gets grey

**Screenshots**
![Screenshot_2023-05-14-22-03-41-47_d0490b14dafa2e72046a4566e3d7d027](https://github.com/astubenbord/paperless-mobile/assets/12736979/dcbfb5ba-f228-40e5-88e1-34bf99f11e4e)

Device Information:

Device: OnePlus 9 Pro
OS: Android 13
Paperless Mobile version 2.2.6+34
Paperless Server version 1.14.4 (API v3)

**Comment by astubenbord** [comment]
I've already got it fixed locally, but it'll take some days until I can publish the update as I don't have time at the moment.

**Comment by astubenbord** [comment]
Should be fixed with 2.3.0. Should be published either today or tomorrow.
