### ISSUE TITLE
[BUG] sync of correspondent not working

### ISSUE THREAD

**Issue by reichelper** [astubenbord/paperless-mobile#182]
Please check the synchronization of correspondents, which are not showing in the app, although several exist on the server.

**To Reproduce**
1. Go to 'lables'
2. Click on 'correspondent'
3. no correspondent are listed, but the server has some

**Device Information:**
 - Device: [Samsung Galaxy S20+]
 - OS: [Android 13]
 - Paperless Mobile version [2.3.2]
 - Paperless Server version [1.14.5]

**Comment by astubenbord** [comment]
Have you tried to perform a fresh install? Sometimes the app does not work as expected when updating.

**Comment by reichelper** [comment]
Yes, I did a fresh install, but the problem still exists.

**Comment by astubenbord** [comment]
Unfortunately I cannot reproduce this behavior. Are you logged in as a superuser? Maybe it's a permissions problem?

**Comment by alexzeitgeist** [comment]
After transitioning from Paperless-ng to Paperless-ngx, I've noticed the same synchronization problem concerning correspondents between the server and paperless-mobile.

Specifically, newly added documents in Paperless-ngx don't display correspondents on the mobile application, despite them being visible on the web interface.

Furthermore, after clearing app data and logging back into Paperless-mobile, all correspondents have disappeared, including those previously visible when utilizing Paperless-ng.

![Screenshot_20230530_234231](https://github.com/astubenbord/paperless-mobile/assets/4434883/4fd1280e-48a5-4502-aa78-07566b5b6e60)

![Screenshot_20230530_234236](https://github.com/astubenbord/paperless-mobile/assets/4434883/a5a2a3ab-536b-4ff6-b1ad-87df838ea319)

Let me know if I can do any further testing.

Alex

**Comment by astubenbord** [comment]
Okay, then I guess there's either an issue with the request Params or the correspondent serialization. I'll check. Thanks for your help

**Comment by astubenbord** [comment]
I unfortunately cannot reproduce this bug. However, I've added some debug statements related to the loading of labels, if anyone experiencing this bug could run the app and run `flutter logs`, maybe there's an error thrown at some point. If you find something like a stack trace, please let me know. The new version containing these statements will be out either today or tomorrow (just have to wait for Google Play to approve). Thanks

**Comment by schtibal** [comment]
Happy to help however I can - can you point me in the direction of figuring out how to run flutter logs?

**Comment by astubenbord** [comment]
Sure, you'll have to install flutter though. Please refer to https://docs.flutter.dev/get-started/install, should be pretty well documented. The just connect your device and run `flutter logs` in the console.

**Comment by alexzeitgeist** [comment]
Anton, good news from my side. It's working all fine now with the latest 2.3.3 release downloaded from GitHub. 👍

I noticed that the latest version on Play is still 2.1.0, which was released three months ago. That's the version I was experiencing the aforementioned issues with.

**Comment by schtibal** [comment]
I've also installed 2.3.3+2038 from github, and it appears to be working as expected. There is a slightly different issue related to document types which I'll continue in the #190 thread

**Comment by astubenbord** [comment]
> I noticed that the latest version on Play is still 2.1.0, which was released three months ago. That's the version I was experiencing the aforementioned issues with.

Yeah, the newest versions are currently in the open beta because of instability, I'll fix some more bugs and publish an official release the next days
