### ISSUE TITLE
Appearance isn't stored after leaving app, v2.3.0

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#183]
I can set the appearance to 'light' but once I have closed and reopened the app it is back to 'dark'. Looks like the appearance isn't saved.

**Comment by astubenbord** [comment]
I've also noticed, will investigate once I have time.

**Comment by marvinwankersteen** [comment]
With me it's the other way round. I want to have dark, but it changes back to light. So I saved light and it changes back to dark when I open it again ;-)
