### ISSUE TITLE
Einstellungen nicht aufrufbar 

### ISSUE THREAD

**Issue by ThexTobi** [astubenbord/paperless-mobile#187]
Gerät: Pixel 7
Version: 2.1.0

Problem:
Sobald auf "Einstellungen" geklickt wird, wird versucht die Einstellungen zu laden, allerdings bleibt der Titel halb transparent und nichts passiert. 
Die App stürzt NICHT ab. Per zurück kommt man wieder zurück.

(Vorausgesetzt in den Einstellungen gibt es auch tatsächlich Einstellungen)

**Comment by astubenbord** [comment]
Hi, bitte nehme entweder an der Open-Beta in Google Play teil oder installiere [die neuste APK direkt von GitHub](https://github.com/astubenbord/paperless-mobile/releases/tag/v2.3.2) herunter. Es wäre ebenfalls noch wichtig zu wissen, welche paperless-ngx version du nutzt. Dem Bug nach zu urteilen wahrscheinlich >1.14.0, richtig?

**Comment by ThexTobi** [comment]
Hey,

danke für die schnelle Antwort.
Das Beta Programm hat das ganze Problem schon gelöst.
Bzgl. paperless-ngx Version: 1.14.5

Danke.

Anton Stubenbord ***@***.***> schrieb am Do., 1. Juni 2023,
20:49:
