### ISSUE TITLE
[BUG] Document types not shown

### ISSUE THREAD

**Issue by schtibal** [astubenbord/paperless-mobile#190]
**Describe the bug**

**To Reproduce**
1. Go to Documents view, and instead of a document type, there is just nothing
2. Click on Labels
3. Select the "Document Type" icon
4. And it says "You don't seem to have any document types set up"

**Expected behavior**
 - Document list view should show the document types
 - The list document types should show, well, the list of document types

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Device Information:**
 - Device: OnePlus 8Pro
 - OS: Android 13
 - Paperless Mobile version 2.3.0+35
 - Paperless Server version v1.14.5

**Additional context**
I signed into the beta to fix the blank "Settings" page - #122 then noticed that my document types are not longer shown. Possibly similar to #182 ??

I cleared the cache and data, uninstalled and re-installed the app, and still the document types were not shown.
On the mobile app, if I try to add a document type that already exists, it fails silently. If I try to add a new document type, it adds successfully, and I can see it in the web UI and  the mobile.
If I subsequently delete that new document type using the web UI, it stays visible in the mobile app and I can't delete it.

**Comment by schtibal** [comment]
This appears to be related, but I just created a new view (using the web UI) that filters on document type. The view appears in the mobile app, but it doesn't filter on doc type (probably because the mobile app appears not to know about my document types)

**Comment by astubenbord** [comment]
That's interesting, the app actually doesn't have to know about your document types as it just queries for the I'd specified in the view. I'm starting to think this is a permissions issue 🤔

**Comment by schtibal** [comment]
What sort of permissions issue? I only have one user, and that user is an admin. It's the same user that I'm logging into both the web ui and the mobile app with. Unless you mean an internal permissions issue/bug within the mobile app?

I've also cleared cache, data and re-installed the app with the same results repeating.

**Comment by schtibal** [comment]
I'm seeing a common thread across document types and tags as well. Adding new ones through the web UI, and them not appearing the mobile app. Strangely though, new correspondents do seem to appear in the app - whereas @reichelper reported correspondents doing this in #182

**Comment by astubenbord** [comment]
Please see https://github.com/astubenbord/paperless-mobile/issues/182#issuecomment-1574970469

**Comment by schtibal** [comment]
App version 2.3.3+2038 appears to have fixed the issue, however I have a possibly related observation. I've created a view called "Manuals" using the web ui, and all it does is filter all documents of type "Manual".  The view is visible on the mobile app, but it shows all documents, not just the ones of type "Manual".

If I go to Labels, select document types, scroll down to my "Manual" document type and click the link icon, I do get a list only documents of the "Manual" type.

**Comment by astubenbord** [comment]
You're right, I can reproduce. I'll have a look

**Comment by astubenbord** [comment]
Okay, there was an error when converting from document filter to the saved view/filter rule. I'll double check the others as well, thanks for noticing :)

**Comment by astubenbord** [comment]
I'll close this one as it's already fixed. Created a separate issue from your comment.
