### ISSUE TITLE
[BUG] Login timeout - DioError

### ISSUE THREAD

**Issue by Jopo-JP** [astubenbord/paperless-mobile#194]
**Describe the bug**
There seems to be a login bug.
If i login into the app, everything is fine, but if an another user (superuser) is trying to login with his account, he will get a timeout error.
This also happens if we switch devices and try to login.
Both users, can login perfectly fine on the webpage.
I'm on a local network and have the current version installed.
This seems to be the case for the android version and ios version.

**To Reproduce**
1. Typ in server url.
2. Test connection, app reports connection is fine.
3. Typ in username.
4. Typ in password.
5. See error `DioError [recieve timeout]: The request took longer than 0:00:15.000000 to receive data. It was aborted.`

**Expected behavior**
To be logged in as the user.

**Device Information:**
 - Device: OnePLus 9 Pro, iPhone 14 Pro
 - OS: Android 13, iOS 16
 - Paperless Mobile version: 2.3.3+2038
 - Paperless Server version: 1.15.1

**Additional context**
As said, if i login, everything is fine, if another user tries to login, he will get a timeout.
In the normal logs, there isn't anything regarding that.

**Comment by astubenbord** [comment]
Do you run paperless on lower-end hardware by any chance? I have also had this happened when I recently down-graded my NAS, and I also think that I decreased the timeout limit. I just checked and indeed: https://github.com/astubenbord/paperless-mobile/blob/3161343c35115f43cb9d34a2c0e32cd2660ef4f0/lib/core/security/session_manager.dart#L24

The limit was reduced here. Maybe your sever is actually taking longer to respond? But if that's the case it's weird that the initial user can login without any problems. Is there any problem when logging in as the admin first and switching to another user?

Just some initial thoughts, I'll have to have a closer look.

**Comment by astubenbord** [comment]
Okay, so definitely not a server bottleneck. But knowing that this issue only occurs when switching accounts narrows it down quite a bit. I'll report back once I've got some news or need additional information.

**Comment by astubenbord** [comment]
HI Nikolas, 

I'd be glad to help. If you feel comfortable sharing this information with me, feel free to send me the guest credentials (url + username + password) to paperless-mobile@protonmail.com so I can have a look. It might make sense to create two guest accounts to test what you are describing.

Greetings back from Germany, 
Anton

**Comment by astubenbord** [comment]
Is this issue resolved?
