### ISSUE TITLE
[Feature] Add more sort options (created and added)

### ISSUE THREAD

**Issue by Totil-a** [astubenbord/paperless-mobile#20]

**Comment by astubenbord** [comment]
What exactly do you mean?

**Comment by Totil-a** [comment]
Sort the documents overview not just alphabetically but also by the date the document was created or added.

**Comment by astubenbord** [comment]
This is already implemented. See the document filter panel and then there are several chips under the "Sort by" header which you can select. It's not the best placement, I know, if you have a better idea on where to put this let me know and I'll think about it

**Comment by Totil-a** [comment]
Ah...now I see. Totally missed the panel.

What could work is adding a filter icon at the top to bring up the filter panel. 
Or allow the panel to slide from the top and not pull it up from the bottom.

I was using the paperless website so far and was used how things are organised in there. (Sort and filter options are in one place at the top)

**Comment by astubenbord** [comment]
I implemented this in the newest release (v1.1.0-beta). I'd be glad about some feedback :)
