### ISSUE TITLE
[BUG] Not showing any document

### ISSUE THREAD

**Issue by SHU-red** [astubenbord/paperless-mobile#206]
**Describe the bug**
Opening the app does not show any document
No filter is active
I am connected via local network to my docker containerized paperless-ngx

**To Reproduce**
1. Open app
2. Go to Documents
3. Nothing shows up

**Expected behavior**
I can see all my documents
If i use the WebUI of Paperless-NGX all my documents can be seen

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Device Information:**
 - Device: Google Pixel 6
 - OS: Android 13
 - Paperless Mobile version 2.3.5
 - Paperless Server version 1.15.1

**Additional context**
- It has worked before
- Also at my parents house it has worked before but not anymore --> Do more people have this issue?
- All Tags etc. can be seen but only documents do not appear and can not be found via search

**Comment by astubenbord** [comment]
Hi, could you try to perform a fresh installation of the app?

**Comment by SHU-red** [comment]
I did

1. Clear Data and cache of app
2. Uninstall app
3. Reinstall app

Still no documents occur

I hope there is no filter active or something
But after a reinstallation nothing should be?!

**Comment by astubenbord** [comment]
You're right, no persistent data, including the document filter, should be left after clearing app data.
What permissions does your user have? Is it a super user or a regular user?

**Comment by SHU-red** [comment]
Not sure what you are asking for
- The app is on my android phone which is not rooted or unlocked
- The paperless-ngx docker-container is running on my homeserver via portainer/docker-compose

**Comment by astubenbord** [comment]
I meant the paperless user you're logging in with :)

**Comment by SHU-red** [comment]
Ah sure,
i have created users
- Superuser --> Not seeing any documents from app (seeing all documents via WebUI)
- MyUser --> Not seeing any documents from app (seeing all documents via WebUI)

**Comment by astubenbord** [comment]
Would it be possible to check the logs of the app? The app logs all network requests, maybe there is a (hidden?) filter active which  prevents any documents to be loaded since there is no match? What exactly is shown on the screen? Could you post a screenshot?

**Comment by SHU-red** [comment]
I will provide everything you want

Where is the log section?

**Comment by astubenbord** [comment]
You'd have to connect your device to your PC and run `adb logcat | grep flutter` (if you have adb installed) or `flutter logs` (if you have flutter installed).

**Comment by astubenbord** [comment]
Please update the app in google play, the latest version 2.3.6 should now be available, which adds more debug output to the log.

**Comment by astubenbord** [comment]
Thanks for the logs, will be fixed in the next release. Already scheduled, may be up by the evening.
