### ISSUE TITLE
Can not login since latest update [BUG] 

### ISSUE THREAD

**Issue by Morethanevil** [astubenbord/paperless-mobile#211]
**Describe the bug**
After update of the app, I was logged out and now I can not login anymore. I get an error message. See Screenshot. The mobile webpage of paperless works without any issues.

**Screenshots**
![IMG_20230615_211059](https://github.com/astubenbord/paperless-mobile/assets/110860055/612a05fb-340b-4c9b-b25b-26a12af24d40)

**Device Information:**
 - Device: Oneplus 9 Pro 
 - OS: Android 13
 - Paperless Mobile version latest
 - Paperless Server version 1.15

**Comment by tmpillbox** [comment]
I'm getting something similar. The error shown is

```
type 'String' is not a subtype of type
'Map<String, dynamic>'
```

Same error for both users of my server.

**Comment by astubenbord** [comment]
Could you please specify the actual app version? It's sometimes not clear since there is also a beta program with newer versions. Thanks

**Comment by Morethanevil** [comment]
I have switched to beta, because I thought it would fix this. Playstore says v2.3.8

**Comment by fastcrash** [comment]
Hi, I get the same error as the TO. Version 2.3.7 on Android 12.

**Comment by astubenbord** [comment]
Could someone (preferably all) run `flutter logs` or `adb logcat | grep flutter` when this occurs? I could not reproduce the issue yet unfortunately

**Comment by Willi-P** [comment]
I am getting also
`type 'String' is not a subtype of type
'Map<String, dynamic>'`
since the last update to 2.3.7

**Comment by fr567** [comment]
Same here (Version 2.3.7+42, Android 10), but not for the admin user, but for another user with limited rights. I get this error message:

```
DioError [unknown]: null
Error: Instance of 'ServerMessageException'
```

Enclose the limited rights for the user. Not sure, if it has something to do with it.
![rights](https://github.com/astubenbord/paperless-mobile/assets/92477674/05f289e9-7d35-4262-aa88-e9c17727837e)

**Comment by astubenbord** [comment]
Oh well. Very important information for all of you: Every user currently needs at least the UISettings -> View and Users -> View setting! Otherwise the app cannot know which user is currently logged in and what I'd this user has!

Maybe check if this is the case. If your users have these rights and it still doesn't work, I'll need the logs from the app.

**Comment by fastcrash** [comment]
@astubenbord that helped. Thanks!

**Comment by fr567** [comment]
I now set all rights for the type "User:" and now it is working again. Thanks for the hint! But is this the expected behaviour?


![Image](https://github.com/astubenbord/paperless-mobile/assets/92477674/17760c6b-862e-4508-b607-bbb3e7796793)

**Comment by astubenbord** [comment]
Yes it is, I can probably make it work with just the UISettings. It's interesting that the webUI works as expected without UI settings permission.

**Comment by fr567** [comment]
Thanks for the feedback and the very cool App! So you can also restrict the usage of the App for some user ;-).

**Comment by Morethanevil** [comment]
> Same here (Version 2.3.7+42, Android 10), but not for the admin user, but for another user with limited rights. I get this error message:
> 
> ```
> DioError [unknown]: null
> Error: Instance of 'ServerMessageException'
> ```
> 
> Enclose the limited rights for the user. Not sure, if it has something to do with it. ![rights](https://user-images.githubusercontent.com/92477674/246390047-05f289e9-7d35-4262-aa88-e9c17727837e.png)

This fixed my issue. Maybe a hint could be given in the readme about permission 🤔

Readpermission is enough. I leave the issue open so others can find it better.

**Comment by tmpillbox** [comment]
> I'm getting something similar. The error shown is
> 
> ```
> type 'String' is not a subtype of type
> 'Map<String, dynamic>'
> ```
> 
> Same error for both users of my server.

I'm guessing this is actually a different error than the one posted. I'll report a new bug, I suppose.

**Comment by astubenbord** [comment]
> > I'm getting something similar. The error shown is
> > 
> > ```
> > type 'String' is not a subtype of type
> > 'Map<String, dynamic>'
> > ```
> > 
> > Same error for both users of my server.
> 
> I'm guessing this is actually a different error than the one posted. I'll report a new bug, I suppose.

Yeah, I think so, too.

**Comment by astubenbord** [comment]
@tmpillbox what paperless (server) Version are you on?
