### ISSUE TITLE
[BUG] Crash when taking an image

### ISSUE THREAD

**Issue by ata-star** [astubenbord/paperless-mobile#214]
**Describe the bug**
When trying to crop the Scanned image, the app crashes

**To Reproduce**
1. Go to 'Scanner'
2. Click on 'Scan'
3. Scan anything or Document
4. See the error

**Screenshots**
![Screenshot_20230618-130535](https://github.com/astubenbord/paperless-mobile/assets/62115669/76781c4d-75dc-4fd8-bd44-b1cad4c15e85)

**Device Information:**
 - Device: Motorola g22
 - OS: Android 12
 - Paperless Mobile version: 2.3.7+42
 - Paperless Server version: 1.16.1

**Comment by ata-star** [comment]
it works when opening an existent image
seems like it cant use the Buildin camera, adjusting issue

**Comment by astubenbord** [comment]
Hi, unfortunately I do not have any control over the current scanner. I use the edge_detection library, maybe create an issue there. 

We do plan however to implement a custom scanner. But that will take several months.

**Comment by ata-star** [comment]
the edge detection seems to work on an imported image

**Comment by astubenbord** [comment]
Cropping is also part of that library :/

**Comment by ata-star** [comment]
i see

**Comment by astubenbord** [comment]
I'll close this in favor of #322
