### ISSUE TITLE
App suddenly stopped working - Instance of ServerMessageException

### ISSUE THREAD

**Issue by sbrunsch2024** [astubenbord/paperless-mobile#218]
Paperless App without mobile in name works, web access also.

![Screenshot_20230622-193036](https://github.com/astubenbord/paperless-mobile/assets/137435496/c03422aa-e205-4032-8058-305a8c788281)

Paperless ngx version is 1.16.2

Smartphone is Pixel 7 Pro with Android 13 Xiaomi Pad 5 with Android 13.

It worked before.

Paperless ngx version 1.16.3 is also not working.

**Comment by astubenbord** [comment]
Hi, I assume the user you're trying to login with lacks the UISettings -> view and User -> view permissions. Try to assign those and see if it works. Otherwise please report back. Thanks

**Comment by sbrunsch2024** [comment]
added following rights and it seems to work...

![grafik](https://github.com/astubenbord/paperless-mobile/assets/137435496/ee4b03fc-02b8-4a39-ab25-c28b508c4b04)

**Comment by astubenbord** [comment]
Good to hear. I've added a hint about the required permissions to use the app in the latest beta version, maybe consider joining the open beta on google play (or use the latest release from GitHub). Unfortunately, there is no way to access user information other than through UISettings. I may be able to remove the requirement for user permissions at some point though.

**Comment by JigSawFr** [comment]
@astubenbord not possible to check with API error code ? If it’s different with a wrong login/pwd combo.

**Comment by astubenbord** [comment]
@JigSawFr I don't understand exactly, the app does check API codes, but the error is not correctly displayed because it is apparently not caught.
