### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by haddadnj** [astubenbord/paperless-mobile#226]
Since #33 is locked I'm adding a new issue, I'm sorry if this isn't the preferred spot!

Is the team open to supporting iOS? I would be willing to handle deployments and App Store admin stuff with a developer account.

Let me know!

**Comment by JigSawFr** [comment]
Hello @haddadnj 
We already deliver iOS versions via TestFlight: https://github.com/astubenbord/paperless-mobile/discussions/204
Working on integration to global project and releasing to Apple Store.
Have a nice day,
