### ISSUE TITLE
More convenient way for tagging

### ISSUE THREAD

**Issue by sarakha63** [astubenbord/paperless-mobile#23]
When we have lots of tags, it's difficult to apply tags for documents.

Something like paperless does on it's ui would be nice.

A kind of search box which will filtrer dynamically the list.

It could also be great to be able to add a New tag directly when editing a document (same for New correspondent and type)

PS : this app is wonderfull. A really great companion. Thanks for sharing

**Comment by astubenbord** [comment]
Hi, thanks :)
I had this implemented exactly as you described, but there is a major bug in the ChipsInput library which unfortunately makes it unusable, as the keyboard closes itself. I'll either have to implement it myself or have to wait until there is an update to the library (I think I remember it's not even a bug with the library but with flutter itself). The current solution is just temporary until I find the time to properly implement it.

**Comment by sarakha63** [comment]
Ok great news

Keep on your good work

**Comment by astubenbord** [comment]
Implemented in https://github.com/astubenbord/paperless-mobile/releases/tag/v1.0.6-beta.
