### ISSUE TITLE
[FEATURE] Allow use of flashlight when scanning

### ISSUE THREAD

**Issue by Phiwa** [astubenbord/paperless-mobile#231]
**Feature Request:**

When scanning documents the results can usually be improved by activating the mobile's flashlight which is an option in other document scanner apps (e.g. OfficeLens, Docutain, OpenScan, Open Note Scanner).
Would be great to have a button to enable the flashlight in document scanning mode. Since Paperless-Mobile uses (and therefore occupies) the camera it is not possible to enable the flashlight manually before scanning.

**Device Information:**
 - Device: OnePlus 8 Pro
 - OS: Android 13
 - Paperless Mobile version: 2.3.9+44
 - Paperless Server version: 1.16.5
 
If there already is such a functionality and I missed it, just give me a hint please. 😉
And thanks for this great app of course!

**Comment by astubenbord** [comment]
Hi, i currently use the edge_detection library, this is very likely related to https://github.com/sawankumarbundelkhandi/edge_detection/issues/122. I'll check what can be done to always show the flash option, but I'm working on a custom scanner anyway, but this will take some time

**Comment by Phiwa** [comment]
Ah, good to know it is not a general issue, but related to my device.
Thanks for looking into it!

**Comment by Phiwa** [comment]
Flashlight button is now visible, probably because of the fix mentioned in the linked issue. 👍 

Thanks again for a great app!

**Comment by anilkumar416** [comment]
Is that issue fixed? I am still not able to see flash button
