### ISSUE TITLE
[BUG] Creating new label is not possible (e.g. during upload)

### ISSUE THREAD

**Issue by loddi** [astubenbord/paperless-mobile#233]
When you prepare a new document for uploading, creating a new label is not possible. You get a blank screen when doing so.

**To Reproduce**
1. Take a photo of the document
2. Click on "upload".
3. Click on Tags
4. Write the name of a new label
5. Click on "new tag"

**Expected behavior**
A screen is shown in which you can create a new label

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Device Information:**
 - Device: Google Pixel 6a
 - OS: Android 13
 - Paperless Mobile version 2.3.9
 - Paperless Server version 1.16.5

![1](https://github.com/astubenbord/paperless-mobile/assets/3449302/bec61728-1aa2-4028-95a8-9a21dc177141)
![2](https://github.com/astubenbord/paperless-mobile/assets/3449302/0ea09a39-b51f-4a63-9e82-fa5ba65d1381)
![3](https://github.com/astubenbord/paperless-mobile/assets/3449302/b774c320-fdae-474e-9655-6fb603c0a2ef)

**Comment by Kaskadeur111** [comment]
Same here. No Corespndent, no Tag, no Document Type possible. Just a Grey screen.

**Comment by astubenbord** [comment]
Hey, thanks for reporting. I just fixed it, will try to upload a new release with some bug fixes including this today

**Comment by andritolion** [comment]
I get this gray screen when trying to add a correspondent from the correspondent tagging option when a search turns up no results.

**Comment by HWiese1980** [comment]
I'm also still seeing this bug.

**Comment by astubenbord** [comment]
Yup, I'm almost finished with the rework and stable multi user update, will publish this week

**Comment by lmanning88** [comment]
I'm seeing the same issue when editing an existing document, screens all look the same though so assume that will be fixed in the new release as well, thanks very much

**Comment by ITCMD** [comment]
Also having this issue both on new documents and edits. Glad to hear a fix is coming. Thank you for this awesome app!

**Comment by astubenbord** [comment]
Alright guys, I just submitted the new version for review to the open beta!
