### ISSUE TITLE
Document Preview in Edit Screen.

### ISSUE THREAD

**Issue by Kaskadeur111** [astubenbord/paperless-mobile#234]
It would be VERY convenient to see a document preview below the entry fields when editing a document.

I always have to switch back and open the document just to check if the date is right or if the correspondent is correct or just to see the Title of the document (which is mandatory when editing).

![Screenshot_20230722_093238.jpg](https://github.com/astubenbord/paperless-mobile/assets/28257942/15daa660-69f7-499b-ad8d-b962c9a7af43)

**Comment by astubenbord** [comment]
Hi, that's a good idea and shouldn't be hard to implement. Any idea on how this should look like? I don't think I can show both edit fields and the preview at the same time. I thought of a toggleable bottom sheet/right side drawer? Please let me know your thoughts

**Comment by Kaskadeur111** [comment]
Sounds good. Yes, a button which floats in a preview from bottom or right should be fine. :-).

**Comment by astubenbord** [comment]
This is implemented in the latest versions.
