### ISSUE TITLE
Save the grid view

### ISSUE THREAD

**Issue by sarakha63** [astubenbord/paperless-mobile#24]
We Can select the grid view. It works and it's nice. But this isnt saved. Each time we come back to document tab. It resets to list view.

PS : this app is wonderfull. A really great companion. Thanks for sharing

**Comment by astubenbord** [comment]
will do

**Comment by sarakha63** [comment]
Eheh thanks again

👍

**Comment by astubenbord** [comment]
Implemented in https://github.com/astubenbord/paperless-mobile/releases/tag/v1.0.6-beta.

**Comment by sarakha63** [comment]
OHHHH yeahhh that was hell a fast.

I tested it, it's working GG


I would like to mention one thing , when i updated the app trough play store

It kept freezing once launched , it stayed on the splash screen with the leaves

I had to clear data and then it launched


I don't know if its related on something on my side or due to something changed in the update but i prefer to mention it in case it hides something @astubenbord

**Comment by astubenbord** [comment]
Yes this is expected. I've changed the way settings are serialized, a new install is recommended. I will add this to the release notes. I thought about writing a migration script but given the few users this app has right now and that it's still in beta it isn't really necessary.
Cheers

**Comment by sarakha63** [comment]
yes and this is only 3 param to remake the connection. that is not quite a big issue
