### ISSUE TITLE
[BUG] Upload of files messes up file names

### ISSUE THREAD

**Issue by mcenno** [astubenbord/paperless-mobile#242]
When uploading a file from my Android the file name is changed from, e.g., "file.pdf" to "filepdf.pdf". When uploading the same file through the paperless-ngx server web interface, the file name is left unchanged.

1. Go to Scanner
2. Click on "Upload a document from this device"
3. Select a PDF
4. After ingestion into paperless-ngx, the file name is changed as described above.

Expected behaviour:
Files with existing extensions are left untouched, files without extension are renamed to include a meaningful extension.

 - Device: Google Pixel 4a
 - OS: Android 13
 - Paperless Mobile version: 2.3.9
 - Paperless Server version: 1.16.5

**Comment by astubenbord** [comment]
Should be fixed in 3.0.1 and later.
