### ISSUE TITLE
[BUG] Inbox unread document count not only increasing 

### ISSUE THREAD

**Issue by doluk** [astubenbord/paperless-mobile#245]
**Before submitting a bug report**

- [ x ] I have looked through [existing issues](https://github.com/astubenbord/paperless-mobile/issues?q=is%3Aissue) and found no similar issue that is either open or has already been fixed
- [ x ] I have read the [troubleshooting section](https://github.com/astubenbord/paperless-mobile#troubleshooting) in the repository's README
- [ x ] I have tried to re-install the app, and the issue still occurs. The app is still subject to breaking changes, requiring a fresh installation or at least clearing app data after updating.

**Describe the bug**
The inbox notification reddot number (sorry i dont know what the proper name is) doesnt update after reading an/all unread document. Resulting in an only increasing number, even if there are no unread documents left.

**To Reproduce**
1. Upload one document 
2. Click on inbox and open the newly uploaded document and change a tag or the name and click on save.
3. Go back to the overview.
4. If you look now at the inbox item at the bottom left, there is still the indicator for an unread document.

**Expected behavior**
Expected is the indicator count drops/gets removed when reading a previously unread document.

**Screenshots**
https://github.com/astubenbord/paperless-mobile/assets/69309597/75170241-b338-43fd-a2d4-271629de1756

**Device Information:**
 - Device: Samsung Galaxy S21 5G Ultra
 - OS: Android 13 One UI 5
 - Paperless Mobile version: 2.3.9+44
 - Paperless Server version: v1.16.5 API v3

**Comment by doluk** [comment]
Great project btw, really appreciate the work you put in!

**Comment by doluk** [comment]
Ah it looks like editing the tags/name removes it from the inbox visually but doesnt mark it as seen

**Comment by astubenbord** [comment]
Thanks for noticing, I'm currently reworking some of the app mechanics, this'll be fixed in the next update :)

**Comment by astubenbord** [comment]
Could you check if this is resolved in the latest version (3.0.6)?

**Comment by doluk** [comment]
Yes it is kinda fixed. I wasn't able to reproduce the inbox notification. So I couldn't really proceed further. I like the new look and flow for uploading a document!

**Comment by astubenbord** [comment]
Thanks, I'll close this then.
