### ISSUE TITLE
Unknown error when uploading a file

### ISSUE THREAD

**Issue by rafal72934** [astubenbord/paperless-mobile#248]
I just installed the app and yesterday everything was working. Now I'm getting an "Unknown error" when uploading an existing file or a scan. There is nothing showing up in the logs on the server side.

Device Information:

    Device: OnePlus 10 Pro
    OS: Android 13
    Paperless Mobile version 2.3.9+44
    Paperless Server version 1.17.0

![Screenshot_2023-08-13-16-23-51-50_d0490b14dafa2e72046a4566e3d7d027](https://github.com/astubenbord/paperless-mobile/assets/109241638/7dd2a44d-6ed6-438f-b557-e03bdf8128ba)

**Comment by marlonbasten** [comment]
Is there a way to fix it or an ETA when it will be fixed? Thanks!

**Comment by astubenbord** [comment]
I didn't have the time to look at it yet, so I unfortunately cannot help by pointing you to code or a general direction where this may originate from. If I had to guess when I'll be able to work on the app more frequently again, it'd probably be around mid of September (currently end of master's and then two weeks out of house).

Cheers

**Comment by astubenbord** [comment]
Hi, could you check if this is still the case with the newest version (3.0.1 either here on GitHub or Google Play Beta)?

**Comment by rafal72934** [comment]
Seems to be working now. Thank you!

**Comment by astubenbord** [comment]
Good to hear. I will close this, feel free to reopen if you encounter this issue again.
