### ISSUE TITLE
[feature request] Quick-scanning workflow

### ISSUE THREAD

**Issue by flyser** [astubenbord/paperless-mobile#252]
Hi,
first of all thanks for this great app, it makes Paperless much more useful for me :)

I think some kind of quick-scanning workflow would great, where you can scan a lot of documents in succession without having to press so many buttons in between (and therefore without filling in the metadata like correspondents, date and document type and without having to hit the upload button for each document). It could be useful to set a configurable tag on these documents, so their metadata can be added later by filtering by this tag. Or to be able to set *some* metadata before the scanning starts (e.g. "I am scanning all my invoices now" or "I want to scan all documents related to my child").

I would imagine the scanning itself to simply switch back-and-forth between two views:
1. Camera view (just like it exists now, allowing you to crop and deskew the image)
2. Dialog asking if you want to: a) scan another page of the same document, b) scan the next document, c) finish scanning

Regards

**Comment by astubenbord** [comment]
Hi, I currently use `edge_detection` package for the scanner, I'm not sure if it allows for a lot of customization since it wraps a native view. I do plan on writing a custom scanner but that's a lot of effort, so it will probably not be implemented in the near future.

**Comment by astubenbord** [comment]
I'll close this in favor of #322 to track the progress of scanner related issues.
