### ISSUE TITLE
[BUG] Manual date entry doesn't respect device locale

### ISSUE THREAD

**Issue by tomc128** [astubenbord/paperless-mobile#253]
**Before submitting a bug report**

- [x] I have looked through [existing issues](https://github.com/astubenbord/paperless-mobile/issues?q=is%3Aissue) and found no similar issue that is either open or has already been fixed
- [x] I have read the [troubleshooting section](https://github.com/astubenbord/paperless-mobile#troubleshooting) in the repository's README
- [x] I have tried to re-install the app, and the issue still occurs. The app is still subject to breaking changes, requiring a fresh installation or at least clearing app data after updating.

**Describe the bug**
When choosing a date for a document, and tapping the pencil icon to enter the date by text entry instead of the calendar view, the date doesn't correctly respect the devices locale. For instance, the 7th September 2023 is displayed as 9/7/2023 rather than 07/09/2023 which is the correct format for the UK locale.

**To Reproduce**
1. Tap any document to view it
2. Tap the pencil to edit
3. Tap the date field under "created at"
4. Choose a date
5. Tap the pencil icon
6. The date selected will appear in US English instead of the device locale. Additionally, entering a date that isnt necessarily valid in US English, but is valid in your locale will result in an error

**Expected behavior**
The date should respect the device locale

**Screenshots**
![Screenshot_20230907-180807.png](https://github.com/astubenbord/paperless-mobile/assets/43298139/bcb89218-0dfb-4547-8d6e-40f8ed6e6a2f)

![Screenshot_20230907-180818.png](https://github.com/astubenbord/paperless-mobile/assets/43298139/987c9e95-a298-4aa3-b751-7eca852b5a7d)

**Device Information:**
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - Paperless Mobile version: 2.3.9
 - Paperless Server version: 1.17.4

**Additional context**
This is purely an issue in this app, date entry correctly works on the webpage.

**Comment by beyercenter** [comment]
I have another issue with date selection

Date localisation looks correct but with default Samsung keyboard I can not enter dot:

![Screenshot_20231007_145227.jpg](https://github.com/astubenbord/paperless-mobile/assets/23611675/747effa3-2d75-4972-b46f-8a8ef9c043d0)

![Screenshot_20231007_145434.jpg](https://github.com/astubenbord/paperless-mobile/assets/23611675/c48afc2e-c8d6-4e19-951a-7c7157a5b0b3)

Changingto another input keyboard(OpenBoard) I have . and other symbols like @tomc128 

Samsung Galaxy S20, Android 13, One Ui 5.1
