### ISSUE TITLE
Korrespondent 

### ISSUE THREAD

**Issue by NikolausStefan** [astubenbord/paperless-mobile#254]
Hallo,

Korrespondent auf dem Handy kann man nicht hinzufügen.

Mein Handy :
Honor 20 pro
Magic 4.0.0
Android 10

Mfg 

Stefan

**Comment by beyercenter** [comment]
Hallo Stefan,

Schreiben hier nicht alle englisch? 

Ansonsten fehlt der Meldung ein bisschen mehr "Input". Wo und wie versuchst du es und was klappt dann nicht?
Gibt hier ein geschlossenes Issue zum Anlegen von neuen Korrespondenten, Tags etc beim hochladen von neuen Dokumenten. ID such ich gleich raus

Dupplicate of #239  and #233

**Comment by NikolausStefan** [comment]
Ok,
Paperless Server Version 1.17. 4 API v3
Paperless mobile 2.3.9+44
Entwickler Anton Stubenbord 

Wenn ich ein Dokument bearbeiten will und ein Korrespondent hinzufügen möchte, funktioniert es nicht. Die App blockiert auf dem Handy. 

Desweiteren hat die OCR Probleme. Beim einlesen einer Datei egal welchen Formats, jpg, PDF etc, wird nur ca. ein Drittel der Seite als Text erkannt. Das passiert bei 3 von 10 Dateien. Also nicht immer. Sporadisch. Als ich es bemerkte, habe Ich es mit verschiedenen Arten von Rohdaten versucht, verschiedene Formate, verschieden gescannt. Bisher konnte ich nicht feststellen, daß der Fehler aus den Formaten der Rohdaten stammt.

**Comment by astubenbord** [comment]
Hi, 
danke fürs Reporten. Wie Thomas schon anmerkte, es wäre tatsächlich besser die issues auf Englisch zu melden, da es sonst für andere nicht-deutschsprachige Nutzer unmöglich ist, existierende Probleme zu finden.

Könntest Du für die Probleme beim OCR bitte eine separate Issue anlegen? 

Vielen Dank und Grüße

**Comment by G4Cab** [comment]
Same here, Android App v2.3.9, if i want to add a new correspondent, i'll only get a blank screen.

Device Samsung Note9 Android 10

**Comment by astubenbord** [comment]
I'll close this as a duplicate of #233, since this refers to the same issue. I'm currently working on a major rework of the app which should add more stability, but it'll take me some time still. Maybe subscribe to #233 to stay updated.
