### ISSUE TITLE
OCR problems in paperless ngx

### ISSUE THREAD

**Issue by NikolausStefan** [astubenbord/paperless-mobile#255]
Hi,

I noticed two bugs in paperless that can't always be reproduced. Both  OCR problems. 

1.  In 3 of approximate 15 scans, means jpg or pdf without text attached, the OCR-text content is only partially displayed/done in paperless! However, if you are in Paperless and start a new OCR over the same document, it will be displayed correctly and correctly recognized.
2. In 1 of 30 Dokuments, which I ad in paperless as an OCR PDF dokument with Text already attached , are some words shown intermittently in paperless. This means that a whole word search cannot be done correctly. Result is, that the original text in PDF  must be deleted and new OCR must be started in paperless. 
So every scan must be again controlled in paperless for the recognized text.

Thanks in advance for every help! 

Stefan

**Comment by astubenbord** [comment]
Hi, sorry for the late reply! 

Just to be more clear:
1. Does this onlyoccur when uploading via app or also via the paperless-ngx webclient?
2. What paperless-ng(x)/Paperless Mobile versions are you using?

I'm afraid it may be a bug with paperless-ngx and not the app itself, since the app does not have anything to do with the OCR/Document processing, which happens at the server.

**Comment by NikolausStefan** [comment]
Hi,

answer your questions as follow:

1. All 3, from mobile, via webclient and if it takes it selfes from a
cloud, in my case Google drive. Unfortunately, the errors cannot be
reproduced.  As I see it, they are arbitrary.
2. Paperless mobile 2. 3. 9. +44

Stefan Flaman
Dipl.-Ing. (TU)
Hohenzollernstraße 99
66117 Saarbrücken
(what3word: ///lehm.glänzen.matratze )

Anton Stubenbord ***@***.***> schrieb am Fr., 6. Okt. 2023,
18:48:

**Comment by astubenbord** [comment]
Hi, 

thanks for your quick response. Unfortunately, there is nothing I can do about issues regarding the server (which it seems this is). You should probably report this to the paperless-ngx team. Sometimes it helps to restart the server, I've also found it to hang or not properly complete tasks at times. Closing as not planned.
