### ISSUE TITLE
[BUG] App does not start after server name change

### ISSUE THREAD

**Issue by chrishuette** [astubenbord/paperless-mobile#258]
Great Job sofar! Iam a big Fan!

Now i ran into an issue. I had to change the adress of my paperless. changed it from paperless.old.de to paperless.new.de:8010. 

When i try to start the App it shows the paperless symbol, but does not complete loading process. I thought just reinstall and everything will be good. But when i delet it and reinstall it again. it seems like it still has the olddata and tries to connect to the old paperless server. i coulndt find a way to change the serveradress now, that it is already changed. unfortunatly, i cant revive the old adress.

Hope you can understand the issue and you will be able to solve it. 

with great respect,

Christian

**Comment by astubenbord** [comment]
Hi Christian, thanks for your kind words. I think I understand your problem, but could you be so kind and create a list of steps to reproduce the issue? Something like 

1. Open the app
2. Type in server name
3. login
4. close the app
5. open app again
6. add new server 
7. ...

That'd be very helpful in finding the issue! Thanks

**Comment by chrishuette** [comment]
Sure. I did:
1. Setup Paperless sever on a raspberrypi with Docker compose. Port 8010.
2. setup a subdomain forwarding to the paperless container with TraefikHub
3. install Paperless Mobile App on Smartphone (using that subdomain)
4. used it for a long time and was really happy ;)
5. suddenly i couldn't access my server via web nor app using the external
domain. Figured out the issue was due to traefikHub. they stopped their
free-service and my subdomain was no longer pointing to my paperlessserver.
6. Tried to solve the problem by deinstalling paperless mobile app. and
reinstall it. but it seems that it keeps the subdomain i provided in the
beginning. I searched for a possibility, to erase the setting completely,
but found no possibility. If i install it on a new phone i can just put in
a domain and everything ist good.
Maybe the issue is because of the samsung Phone. I was asked during the
installation process if i want to save the login credentials and use
biometrics for logging in. i did take that option. And when i start
paperless mobile (even after a clean reinstall) it asks me to provide my
biometric credentials (fingerprint) and then it hangs in the signing in
process with the paperless logo.

solution ideas:
1. Maybe it is completely my fault and there is a way to clean the
logindata for paperless wich is stored in the biometrics-login feature.
2. Maybe when deinstalling it should automaticly erase any stored logindata
stored in the biometrics-login feature.

But you are the Pro ;)

thanks for coding this awesome app. I hope i was able to help you further
improving it.

with big respect,

Christian Hütten


Am Mi., 20. Sept. 2023 um 12:46 Uhr schrieb Anton Stubenbord <
***@***.***>:

**Comment by chrishuette** [comment]
I just tried it on my wifes phone. I didnt activate the "biometric
authentification at the beginning" back in time. An yes in this case i was
able to just de na reinstall it, fill in the new domain and everything
works again. So Problem for sure is related to that biometric
authentification feature not cleaning the login after deinstall.

hope it'll help.

mit freundlichen Grüßen

Christian Hütten


Am Mi., 20. Sept. 2023 um 18:00 Uhr schrieb Christian Hütten <
***@***.***>:

**Comment by astubenbord** [comment]
Yeah. I remember now. This is very likely related to a bug in flutter_secure_storage.

**Comment by astubenbord** [comment]
Yeah. I remember now. This is very likely related to a bug in flutter_secure_storage. Related to #244

**Comment by beyercenter** [comment]
What if you cancel that fingerprint login?

You should be able to remove the old connection and setup a new one.

**Comment by astubenbord** [comment]
This should fix it, will implement in next release: https://github.com/mogol/flutter_secure_storage/issues/354#issuecomment-1170367152

**Comment by chrishuette** [comment]
I was able to solve the problem by cleaning all the app data and reconnect.
Thanks a lot!

Anton Stubenbord ***@***.***> schrieb am Mi., 20. Sept. 2023,
19:16:
