### ISSUE TITLE
Unable to login to paperless when autologin is enabled

### ISSUE THREAD

**Issue by dariuszszyc** [astubenbord/paperless-mobile#26]
In my paperless-ngx docker instance (behind Traefik proxy) I am using the "PAPERLESS_AUTO_LOGIN_USERNAME" environment parameter so I don't have to login to paperless-ngx.

This is because I use a separate authentication software (Authelia).

When autologin is enabled - I cannot login from the mobile app.
Once I disable this option - mobile application logins without issues.

Any way to make this work without forcing username + password ?
I don't know - support autologin and/or tokens ?
Even if autologin isn't safe (again - I use Authelia for authentication) - fingerprint access to the mobile app is always some protection.

**Comment by astubenbord** [comment]
I haven't looked into other authentication methods, but I'll have a look and if it's not too much effort I can implement it. Maybe you can give me a short summary on how the auto login works? And how does the authelia relate to this? Does this have to be integrated?

**Comment by dariuszszyc** [comment]
Don't worry about Authelia. It doesn't impact this issue at all. Just wanted to mention my setup.

As for the auto login - that's what I see in their docs:
`PAPERLESS_AUTO_LOGIN_USERNAME=<username>
Specify a username here so that paperless will automatically perform login with the selected user.

Danger

Do not use this when exposing paperless on the internet. There are no checks in place that would prevent you from doing this.

Defaults to none, which disables this feature.`

**Comment by astubenbord** [comment]
Okay, that means that you don't need any login information (i.e. username/password)? Is an authentication token required for API access?

**Comment by astubenbord** [comment]
Unfortunately, there is no way to access the API without any kind of authorization, see https://github.com/paperless-ngx/paperless-ngx/issues/2002.
Therefore this feature can and will not be supported.
