### ISSUE TITLE
Got error "type null is not a subtype of type int in type cast" during login

### ISSUE THREAD

**Issue by SeedDMS** [astubenbord/paperless-mobile#262]
The latest version of paperless-mobile hangs during login after entering the username and password. All it says is "type null is not a subtype of type int in type cast". paperless-ngx has version 1.13.0

I checked the http traffic. The last rest api call was `/api/ui_settings` which even returns reasonable json. I first thought this was related to may own rest api build on top of seeddms, but paperless-ngx shows the same behaviour. I have no clue how to debug this.

**Comment by astubenbord** [comment]
Hi, which app version are you on? Have you tried to re-install the app?

**Comment by SeedDMS** [comment]
The latest 3.0.1 downloaded from the play store yesterday

**Comment by SeedDMS** [comment]
Just did a reinstall, but still the same problem.

**Comment by astubenbord** [comment]
I can reproduce this. Let me see...
Update: Found the error, will publish later. Thanks for noticing

**Comment by SeedDMS** [comment]
I can confirm that it's working again. Do you a more detailed documentation of the paperless api than https://docs.paperless-ngx.com/api/ ?

**Comment by astubenbord** [comment]
Yes and no, since it's a Django project, you _should_ be able to get an open API/swagger specification by using the manage.py. There is a certain command, but I'm not sure how exactly it works. I didn't get it to work yet.
