### ISSUE TITLE
[Bug] Manual date selection is impossible because of missing dot input

### ISSUE THREAD

**Issue by beyercenter** [astubenbord/paperless-mobile#267]
I have another issue with date selection

Date localisation looks correct but with default Samsung keyboard I can not enter dot:

![Screenshot_20231007_145227.jpg](https://github.com/astubenbord/paperless-mobile/assets/23611675/747effa3-2d75-4972-b46f-8a8ef9c043d0)

![Screenshot_20231007_145434.jpg](https://github.com/astubenbord/paperless-mobile/assets/23611675/c48afc2e-c8d6-4e19-951a-7c7157a5b0b3)

Changingto another input keyboard(OpenBoard) I have . and other symbols like @tomc128 

Samsung Galaxy S20, Android 13, One Ui 5.1
 

_Originally posted by @beyercenter in https://github.com/astubenbord/paperless-mobile/issues/253#issuecomment-1751718000_

This is NOT fixed in latest beta

**Comment by astubenbord** [comment]
This seems to be a problem with the framework itself and samsung: https://github.com/flutter/flutter/issues/59685
I've implemented a form field like this: https://mui.com/x/react-date-pickers/date-picker/

Should be much easier and faster now to enter dates :) Will be live in the next update
