### ISSUE TITLE
[Bug]: Can't alter permissions on documents

### ISSUE THREAD

**Issue by Schrolli91** [astubenbord/paperless-mobile#272]
### What happened?

Permissions ape is empty or shows any sort of placeholder

### Steps to reproduce

Edit a document and go to the permissions tab

### Screenshots

![image](https://github.com/astubenbord/paperless-mobile/assets/6043382/223270c6-a871-4294-b1e0-40fbb9eff715)

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

2.3.9+44

### Device

Redmi Note 10s

### Operating System Version

Andoird

### Device Locale

german

### Selected Locale

German

**Comment by astubenbord** [comment]
It's not yet implemented and removed for now in v3.0.* (check out the open beta for the newest versions).
