### ISSUE TITLE
[Bug]: The '+ New View' has no function

### ISSUE THREAD

**Issue by SeedDMS** [astubenbord/paperless-mobile#274]
### What happened?

I suppose that the '+ New View' on the home screen is for adding new views, but nothing happens when clicking/touching on it.

### Steps to reproduce

1. Open the home screen
2. Touch on '+ New View'

I would expect some kind of a dialog to open for configuring the new view

### Paperless-ng*x Version

1.13.0

### Paperless-Mobile Version

3.0.4

### Device

xiaomi

### Operating System Version

Android 9

### Device Locale

german

### Selected Locale

English (US)

**Comment by astubenbord** [comment]
Good catch. I'll just have it open the create view page with the "showOnDashboard" set to true. However, currently these views can only be edited through the documents page. I'll add this at some point, but for now this will have to suffice.

**Comment by astubenbord** [comment]
I also just saw that the route is not properly mounted. Will fix in next update
