### ISSUE TITLE
Unable to assign multiple tags

### ISSUE THREAD

**Issue by samreed10** [astubenbord/paperless-mobile#28]
Hi, I encounter a bug when trying to assign multiple tags to a document. Only 1 tag is able to be chosen from the list, with the selected tag overwriting any existing tags chosen. I'm on v1.1.0+5 and server version is 1.9.2.

**Comment by astubenbord** [comment]
Hi, thanks for creating the issue! I just checked and it's the same for me on this version, this is fixed and I'll publish an update today.

Cheers!

**Comment by astubenbord** [comment]
@samreed10 Hi, sorry, I'm currently implementing an inbox feature, I will publish a new release with the fix and the new feature once that's finished. Should be this week though!

**Comment by astubenbord** [comment]
@samreed10 Sorry for the wait, but I finally got to implement my stuff and fix this bug. Feel free to test the new release and give me feedback if there is still anything that doesn't behave as expected.

Cheers!

**Comment by samreed10** [comment]
Nice, thanks Anton. Seems to be working for me. 👌 Let me know if you have a buy a beer/donation link, to thank you for your time on this.

Thanks,
Sam
________________________________
