### ISSUE TITLE
[Bug]: Laggy Document Uploading and does not return to previous menu upon submitting 

### ISSUE THREAD

**Issue by ITCMD** [astubenbord/paperless-mobile#282]
### What happened?

On the new beta, when uploading a document, creating a new correspondent, document type, or tag lags the app for a moment when opening them menu. Once open everything works as expected, but the + button in the bottom right doesn't appear to do anything.

I realized it is in fact creating the document type, tag, or correspondent properly, but then it is not exiting back to the document creation menu. Additionally, once a document is uploaded, it does not close out the document but instead clears all the fields (although the document *is* saved properly)

### Steps to reproduce

1. Scan a new document
2. Select Tag
3. Type the name of a tag that does not exist
4. click Add new
5. Fill it out and hit +
6. back out and search for the new tag, finding it in the list.
7. Upload the document

### Paperless-ng*x Version

1.16.5

### Paperless-Mobile Version

3.0.6+53

### Device

Galaxy S23 Ultra

### Operating System Version

Android 13

### Device Locale

English

### Selected Locale

English (US)

**Comment by astubenbord** [comment]
I'll check tomorrow, thanks for reporting

**Comment by ITCMD** [comment]
Sure thing! Not sure what causes it. Went in again an hour later and it worked flawlessly.

**Comment by astubenbord** [comment]
Hi, sorry for the wait. I could not yet reproduce this issue. 
On the positive side: The next update will introduce persisted app logs, which can both be viewed from within the app or can be read from a file (new log each day). In case this happens again, you could send me the logs and I'll try to figure this out :)

**Comment by ITCMD** [comment]
Excellent news! I'll come back here if I experience it again. May have been a post-update fluke.

**Comment by astubenbord** [comment]
Oh, I forgot to report back. I think I figured out the issue, or should be fixed in the latest release 3.1.1.
