### ISSUE TITLE
Dates offset by a day

### ISSUE THREAD

**Issue by jabdoa2** [astubenbord/paperless-mobile#284]
When I select a date in the app (android) and save the document all dates are offset by one day. Might be because I am currently located in another timezone than the server? Should work nontheless. 

Thanks for the great app :-)

**Comment by astubenbord** [comment]
Hi, please use the Bug report form, otherwise I'd have to ask you a lot of questions :)

**Comment by jabdoa2** [comment]
Suggestion: Link the Form in the app :-).

**Comment by astubenbord** [comment]
You mean directly to the form instead of the "Choose template" page?

**Comment by jabdoa2** [comment]
![Screenshot_20231019-161751](https://github.com/astubenbord/paperless-mobile/assets/557540/f65c39df-3e58-4e08-a055-94b1ac6043d2)

That link send me to the "plain" issue page.

**Comment by astubenbord** [comment]
That's weird. But I also have the GitHub app installed, so maybe the link didn't work correctly for web. I updated it for the next release to point directly to a new bug report using the form.
