### ISSUE TITLE
[Bug]: Missing dot in filename leading to Paperless reject document

### ISSUE THREAD

**Issue by martin5233** [astubenbord/paperless-mobile#287]
### What happened?

When sharing a scanned document with Paperless Mobile, the user is offered a small dialog, where to input a filename. The filename is prefilled with the current date and 'pdf' or other suffix. If the user simply accepts the proposed filename, a filename without a dot before the 'pdf' is generated and uploaded to Paperless. Paperless then rejects this uploaded file due to an unknown extension.

### Steps to reproduce

- Scan a document with any other app
- Share recorded document with Paperless Mobile
- Paperless Mobile shows a dialog with a proposed filename without a dot before the extension
- Click on upload
- The uploaded document is rejected by Paperless due to an unknown extensions

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

2.3.9+44

### Device

Fairphone 4

### Operating System Version

Android 13

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment]
Hi, please switch to the open beta (v3.0.6 latest). This should be resolved there.

**Comment by martin5233** [comment]
Thanks a lot for your quick reply. It's not urgent for me, I simply wanted to report, what I noticed, as it's a minor, but annoying thing. I will probably wait until it's part of a released version.
