### ISSUE TITLE
sort order is reversed

### ISSUE THREAD

**Issue by jdckr** [astubenbord/paperless-mobile#29]
When having a view, the sort order in the app is reversed to what you see in the webinterface.

The logic here should be altered:
https://github.com/astubenbord/paperless-mobile/blob/a7295fb7396bd9473950b76856fce1b3565af93b/lib/features/documents/model/saved_view.model.dart#L64

Here as well:
https://github.com/astubenbord/paperless-mobile/blob/a7295fb7396bd9473950b76856fce1b3565af93b/lib/features/documents/model/saved_view.model.dart#L83

**Comment by astubenbord** [comment]
Thanks for the hint!
I'll add this in the next release. Should be published this week. 

Cheers!
