### ISSUE TITLE
[Bug]: App freezes on Startscreen

### ISSUE THREAD

**Issue by poweRalph** [astubenbord/paperless-mobile#300]
### What happened?

When starting the app the app freezes on Startscreen (green leafs on black screen).
This bug occurs since the last update.
App was installed via play store.
I'm using a Pixel 8 pro with Android 14

### Steps to reproduce

When starting the app the app freezes on Startscreen (green leafs on black screen).

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

Latest

### Device

Pixel 8 pro

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment]
Hi, did you already try to uninstall and reinstall the app?

**Comment by poweRalph** [comment]
Reinstall solved the issue.
Thanks for the hint.

**Comment by ghost** [comment]
The log says:
HiveError: Cannot read, unknown typeId: 132. Did you forget to register an adapter?

Is this a one time occurence which will be solved by a reinstall or can this happen again?

**Comment by astubenbord** [comment]
Yes, this is most likely due to the update from 2.x to 3.x.

**Comment by ghost** [comment]
I thought I had 3.x before but it's indeed possible. Clearing the app data worked as well.
