### ISSUE TITLE
[Bug]:  Server URL validation misses scheme validation.

### ISSUE THREAD

**Issue by Theboss996** [astubenbord/paperless-mobile#305]
### What happened?

Ich kann mich nicht anmelden gibt kein Feld für benutzername und Passwort

App x mal neu installiert von google

### Steps to reproduce

App öffnen 

### Screenshots

![Screenshot_20231114_153406](https://github.com/astubenbord/paperless-mobile/assets/6815999/21d0a053-da48-482c-83d8-78e9e98f9231)

### Paperless-ng*x Version

1.16.5

### Paperless-Mobile Version

Neuste

### Device

Galaxy S 22

### Operating System Version

Android neuste

### Device Locale

Deutsch

### Selected Locale

None

**Comment by astubenbord** [comment]
Du musst ein Schema vor die URL eingeben, also hier http:// oder https:// 

Falls das nicht funktioniert gerne nochmal melden

**Comment by astubenbord** [comment]
Du musst eins chema vor die URL eingeben, also hier http:// oder https:// 

Falls das nicht funktioniert gerne nochmal melden. 

Ich ändere den Titel des Tickets.

**Comment by Theboss996** [comment]
Thx
