### ISSUE TITLE
[Question] How to get the certificate for authentication?

### ISSUE THREAD

**Issue by Bouni** [astubenbord/paperless-mobile#306]
Hi,

I've setup paperless-ngx on my home server and its running. Now I want to use the paperless mobile app with it but strugle to figure out how to get the cert for authentication. Are there any docs on how to do that?

**Comment by Bouni** [comment]
🤦🏽‍♂️ I'm just too stupid. For some reason the button did not get active once I entered the server URL and now I tried again and it worked. Sorry for the noise ...

**Comment by gregbtm** [comment]
Same issue here. Where do I even get a client cert file? The button doesn't work at all to connect without it.

**Comment by Bouni** [comment]
Enter the URL and then touch somewhere outside the text field, then the button gets active if I remember correctly
