### ISSUE TITLE
[Bug]: Scanner cropping is hard to use and buggy

### ISSUE THREAD

**Issue by lgo** [astubenbord/paperless-mobile#310]
### What happened?

While trying out Paperless mobile (which is awesome!), I ran into some usability issues with scanner cropping.

First, the picture and crop-points are behind the overlay making it hard and confsing to move the crop points. This would be a lot more usable if the image was scaled so it's not overlapping with the overlay at all.

Second, I ran into a situation where the crop had 3 crop points rather than 4. This one perplexed me quite a bit! Here's a screenshot:![Screenshot_20231119-205419](https://github.com/astubenbord/paperless-mobile/assets/1161183/ab8bb252-5a6e-4e6d-8bf9-8d2647b83975)

### Steps to reproduce

I attached the original photo which seems to reproduce it on my device .

![PXL_20231120_040629711](https://github.com/astubenbord/paperless-mobile/assets/1161183/6ab06774-dae5-454b-bf92-784b4a041992)
(note, it's just a grocery receipt - so nothing to worry about)

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

3.1.3

### Device

Pixel 3a

### Operating System Version

Android 12

### Device Locale

english

### Selected Locale

English (US)

**Comment by lgo** [comment]
Ah, it took me awhile to figure out the cropping drag is actually quite cleverly implemented and nice when you figure it out - selecting the corner closest to the touch point.

Still, the 3-point polygons seem to be a usability bug.

**Comment by astubenbord** [comment]
Yeah, I've also noticed this before. However, the scanner is using a native plugin which I cannot change. Therefore I'll close this as not planned since I don't have the time to work on a custom scanner at the moment. Some time in the future I will, but not sure when.
