### ISSUE TITLE
After Update S23 to android 14 app does not start

### ISSUE THREAD

**Issue by MeisterTR** [astubenbord/paperless-mobile#311]
### What happened?

When I open the app I aee online the leave. Notting wlaw Happen. Before I update my s23 Ultra to Android 14 everthing was fine.

### Steps to reproduce

Open the app

### Paperless-ng*x Version

K.a

### Paperless-Mobile Version

3.1.3

### Device

S23 Ultra

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

German

**Comment by astubenbord** [comment]
Hi, have you tried to reinstall the app?

**Comment by MeisterTR** [comment]
thanks, reinstall fixed it
