### ISSUE TITLE
[Bug]: Server-Version not displayed correctly

### ISSUE THREAD

**Issue by nurjns** [astubenbord/paperless-mobile#314]
### What happened?

In "Settings" in the Footer I get the text "Paperless Server Version 0.0.0".
![IMG_20231130_133357](https://github.com/astubenbord/paperless-mobile/assets/15909944/40f3f8e2-d309-48e5-b8a6-c1349c85f0f9)

### Steps to reproduce

Go to "Settings" tab.

### Paperless-ng*x Version

2.0.0

### Paperless-Mobile Version

3.1.3+57

### Device

Xiaomi 13

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

German

**Comment by astubenbord** [comment]
I guess there were changes to the API in Paperless 2.0.0, that's why some things may break. The latest version of paperless that is known to be supported as of now is 1.17.4.
