### ISSUE TITLE
[Bug]: Changes not saved

### ISSUE THREAD

**Issue by lulukkki** [astubenbord/paperless-mobile#316]
### What happened?

When I edit some of the properties of the documents (date, tag, type, title) the changes are not saved.

### Steps to reproduce

1. Click on the pencil to edit some document
2. Change something e.g. date
3. Click on "save changes"
4. Notice that the changes are not saved

### Paperless-ng*x Version

2.0.1

### Paperless-Mobile Version

3.1.3

### Device

Google Pixel 7 Pro

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

None

**Comment by thomas110590** [comment]
Yes, i just noted the same problem.

**Comment by astubenbord** [comment]
Can you provide the output of the log?

**Comment by lulukkki** [comment]
This is the log:

2023-12-04 09:56:19.547	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
Instance of 'PaperlessFormValidationException'
---END ERROR---
---BEGIN STACKTRACE---
#0      PaperlessDocumentsApiImpl.update (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:85)
<asynchronous suspension>
#1      DocumentEditCubit.updateDocument (package:paperless_mobile/features/document_edit/cubit/document_edit_cubit.dart:35)
<asynchronous suspension>
#2      _DocumentEditPageState._onSubmit (package:paperless_mobile/features/document_edit/view/document_edit_page.dart:389)
<asynchronous suspension>

---END STACKTRACE---

**Comment by w0d4** [comment]
I have the same problem. Anything I can provide to help fixing this problem?

**Comment by cmusik** [comment]
The problem is that paperless ngx 2.0 needs additional parameters for the edit request. If you look at the http requests you will see this error:

```
{"custom_fields":["Dieses Feld ist erforderlich."]}
```

**Comment by astubenbord** [comment]
I'll try to push a fix today. However, adding support for custom fields will take longer and there are currently also other features which are more requested (including notes for instance).

**Comment by rajalreadytaken** [comment]
Not sure if this qualifies as a new bug, or an extension of this existing bug. 

Paperless-ngx version 2.1.1
Paperless-mobile version 3.1.4
Android 14 on Pixel 7

1. Make a change to a document  in the mobile app (ie: add or remove a tag) 
2. Click "Save changes" but nothing happens and screen stays the same in the "Edit Document" screen.
3. Check the paperless-ngx web interface and the changes made in the mobile app actually ARE reflected in the document
4. Press the "back" arrow in the mobile app, and it warns about discarding changes
5. Viewing the document in the mobile app does not reflect changes until view is refreshed.

**Comment by departet** [comment]
I have this same issue. Setup Paperless-ngx yesterday with the postgres docker-compose from github.
