### ISSUE TITLE
[Bug] versioncode decreased?

### ISSUE THREAD

**Issue by IzzySoft** [astubenbord/paperless-mobile#321]
It seems like at some point after v3.1.1 (`versionCode: 1055`) you've *decreased* `versionCode` – which e.g. for v3.1.4 is set to 582. Which means updates never reach devices via my repo, for two reasons:

1. never releases are purged immediately after download as they are considered older (lower `versionCode`)
2. even if they'd be shipped, Android would reject them considering them a *downgrade* as the `versionCode` is lower than the one of the installed app

So could you please make sure the `versionCode` is always increased, never decreased? And that the next release has a `versionCode` higher than 1055?

And yes, that's the armeabi APK. I didn't check the others, which most likely have a similar problem.

**Comment by astubenbord** [comment]
Hm that's weird, I'll have a look. Thanks for reporting!

**Comment by astubenbord** [comment]
Okay so I just checked and indeed the version codes have decreased from 3.1.2 onward. I never dealt with the fact that version codes are different for different ABIs until I was working on F-Droid reproducible builds (still am BTW 😅) while also distributing the individual APKs for each ABI, which started around 3.1.2. So I guess the easiest way is to rebuild the latest version with the fixed version codes, retag the branch and remove the ones in between which were lower?
This should only affect users which used F-Droid or GitHub as the source, right? I believe the ABB distributed to Google Play should not be affected by this. Does this sound like a valid solution?

The new version codes would look like this (in the new implementation):
- arm64-v8a: 3058
- armeabi-v7a: 2058
- x86_64: 1058

EDIT: I don't even think I have to remove the two versions with mismatching version codes, right?

**Comment by astubenbord** [comment]
I just updated the latest release to again match the old version code scheme.

**Comment by IzzySoft** [comment]
> I just updated the latest release to again match the old version code scheme.

Looks like that was a success: my updater has fetched and announced it :partying_face:

> This should only affect users which used F-Droid or GitHub as the source, right?

Currently Github and [my repo](https://apt.izzysoft.de/packages/de.astubenbord.paperless_mobile/), right. Have you applied for F-Droid inclusion yet? Your app at least is not listed there currently.

> I believe the ABB distributed to Google Play should not be affected by this

No idea about that, sorry.

> I don't even think I have to remove the two versions with mismatching version codes, right?

The older ones (those "in between")? No, I don't think that's needed.

**Comment by astubenbord** [comment]
Great to hear :)

The F-Droid application is still a WIP (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12573/pipelines), the reproducible builds seem to fail again. But I have some ideas how to fix it, will hopefully be merged soon.

**Comment by astubenbord** [comment]
@IzzySoft Just some more information: I reverted the scheme back to the previous version, but increased the build number so the latest version code is always higher. The F-Droid merge request was finally merged.

**Comment by IzzySoft** [comment]
Yay, congrats! :star_struck: So just some more info from my end, too: about 2 weeks after it became available at F-Droid, I'll remove it from my repo (standard procedure to avoid redundancy and get place for complementary apps; my repo runs on limited personal space). Should you need it back later for some reason, it can always be re-established. I try to keep overlaps low, but exceptions are possible when needed.
