### ISSUE TITLE
[Bug]: Cannot edit documents

### ISSUE THREAD

**Issue by DastardlyDino** [astubenbord/paperless-mobile#323]
### What happened?

Cannot edit any documents every since upgrading to Android 14. After uninstalling and reinstalling I get a notification on initial startup saying app is not compatible with Android 14.

### Steps to reproduce

Fresh install paperless-ngx from f-Droid.
Get notification saying app is not compatible
Dismiss and continue
Try and edit any of the document fields
Nothing happens

### Paperless-ng*x Version

2.1.2

### Paperless-Mobile Version

3.1.1

### Device

S23 Ultra

### Operating System Version

Android 14

### Device Locale

English

### Selected Locale

English (US)

**Comment by astubenbord** [comment]
This might be related to #321. Please uninstall the fdroid version and install from GitHub.

**Comment by DastardlyDino** [comment]
Just tried both the Play Store and GitHub versions of Paperless Mobile. I no longer get the App is not compatible with Android 14 notification. But I am still unable to save any edits I try and make. When I click the save button the app just doesn't do anything. Like it's a dead button. It shows the click animation but the actual action of saving does not occur.

**Comment by astubenbord** [comment]
Could you add the app logs? You can find them under Settings > app logs

**Comment by DastardlyDino** [comment]
Posted logs and a screen recording. Will probably delete comment after 48hrs so it doesn't stay public.
So apparently it does save changes but it doesn't show it. I have save, discard, refresh and then it shows the change. Hopefully the video clarifies what I'm talking about.


https://github.com/astubenbord/paperless-mobile/assets/47339617/9f93d553-223e-4610-b954-a8643d8f204f

[paperless_mobile_logs_2023-12-13.log](https://github.com/astubenbord/paperless-mobile/files/13662327/paperless_mobile_logs_2023-12-13.log)

**Comment by astubenbord** [comment]
Ah of course, could you try and update to 3.1.4? Support for paperless 2.x.x was added in 3.1.3.

EDIT: Nvm, I just read that you already tried that. I'll investigate.

**Comment by astubenbord** [comment]
Unfortunately I cannot reproduce this behavior. However, similar behavior has also been reported in #324. I'll add more logs to the edit workflow so I can see where the issue is. I'll try to publish an update this evening, but I cannot promise it will still go live this week.

**Comment by DastardlyDino** [comment]
Sucks that you can't reproduce the error on your side hopefully the video helped. No worries if you can't get an update out this week. It's a very busy time of year. Thank you for all your help.

**Comment by astubenbord** [comment]
Closed through #327
