### ISSUE TITLE
[Bug]: 3.1.7 broke dark mode?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [astubenbord/paperless-mobile#329]
### What happened?

Dark Mode is no longer being set in the app. This is the app now in dark theme selected

### Steps to reproduce

Update to 3.1.7
Set dark theme.

### Screenshots

![Screenshot_20231220-020143](https://github.com/astubenbord/paperless-mobile/assets/98815412/e04f3702-322b-4f7f-b39e-6c8186424ff1)

### Paperless-ng*x Version

2.1.3

### Paperless-Mobile Version

3.1.7

### Device

Google Pixel 6

### Operating System Version

GrapheneOS

### Device Locale

en-GB

### Selected Locale

English (UK)

**Comment by Stephan-4711** [comment]
Same here Google Pixel 6 pro android 14

**Comment by astubenbord** [comment]
Oh damn, yeah I updated screenshots yesterday and I hardcoded the setting. Sorry, will update asap
