### ISSUE TITLE
[Bug]: Remove Button

### ISSUE THREAD

**Issue by calavera2k** [astubenbord/paperless-mobile#334]
### What happened?

Wenn ein Dokument gescannt wird, lässt es sich über den Remove Button nicht wieder entfernen.

### Steps to reproduce

Login
Scan document
Remove 

### Paperless-ng*x Version

2.1.3

### Paperless-Mobile Version

3.1.8

### Device

Motorola edge 30 neo

### Operating System Version

Android 13

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment]
Hi, could you please provide the log output (can be found under Settings > App Logs). Thanks.

**Comment by calavera2k** [comment]
Hello,

attached is the log.

Greetings Michael

Anton Stubenbord ***@***.***> schrieb am Mo., 25. Dez. 2023,
21:16:

**Comment by astubenbord** [comment]
Hi, attachments don't seem to be appended when replying via E-Mail.

**Comment by calavera2k** [comment]
[paperless_mobile_logs_2023-12-25.log](https://github.com/astubenbord/paperless-mobile/files/13772141/paperless_mobile_logs_2023-12-25.log)

**Comment by astubenbord** [comment]
Thanks. The exception was not caught correctly, so it was never displayed. This will be fixed in the next update.
