### ISSUE TITLE
[Bug]: Save document without function when date is in the future

### ISSUE THREAD

**Issue by FBlass** [astubenbord/paperless-mobile#339]
### What happened?

When a document has a date in the future the Save button is without function. Clicking it does simply nothing, no feedback, no error message. Also nothing visible in the error log of the App (in the settings)

Doing the same in paperless-ngx in the browser works.

### Steps to reproduce

1. Open a document in Edit mode
2. Change the date of the document to something in the future 
3. Try to save the document, nothing happens

### Paperless-ng*x Version

2.1.1

### Paperless-Mobile Version

3.1.8

### Device

Google Pixel 8

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

None

**Comment by astubenbord** [comment]
Sorry for the late reply. You're right, and that is not really a bug but a feature ;-) I'll allow arbitrary dates (like up to 10 years in the future should probably suffice?) since paperless also seems to do so. Will be in the next update.
