### ISSUE TITLE
[Bug]: Wrong server version reported in settings footer

### ISSUE THREAD

**Issue by hermannoffen** [astubenbord/paperless-mobile#340]
### What happened?

Settings footer wrongly reports
> Paperless Server-Version v2.2.1 (API V3)
when my server is still on 1.17.4.

### Steps to reproduce

1. Open hamburger menu.
2. Open Settings.
3. Check footer "logged in as..."

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

3.1.8+403

### Device

Google Pixel 7a

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

German

### Additional Context

Likely related to #314.

**Comment by astubenbord** [comment]
How do you determine the version of your server? Through the web UI? I've often found that the browser caches the response to /api/remote_version/ which then causes the wrong version to be displayed. Maybe try to clear the cache in the browser? There is no location in code where the 2.2.1 could come from. I assume that you are on 2.2.1 but the endpoint is still reporting the old version. Could this be the case?

**Comment by hermannoffen** [comment]
I'm pretty sure, the server version is 1.17.4.
It is explicitly stated in my servers docker compose file.
I just checked the WebUI again in incognito mode, too, so there shouldn't be any cache data.
Is there a way to obtain the actual version from log files? Tried `grep version data/log/paperless.log` without any result.

**Comment by astubenbord** [comment]
You could try to query the endpoint /api/remote_version/ and observe the response and also check what the Header x-server-version (or similar) reports.

**Comment by hermannoffen** [comment]
I've called the API manually now:
```
GET /api/remote_version/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "version": "v2.2.1",
    "update_available": true
}
```
Thus, either the app calls the wrong API endpoint or the API itself always reports the most recent released version?

**Comment by astubenbord** [comment]
Hm that's weird, the app definitely calls the correct endpoint. Could you check what the server version header says?

**Comment by hermannoffen** [comment]
Had some trouble doing the request, as I'm currently on my mobile device only. But finally I managed to get the header:
```
HTTP/1.1 200 OK
date: Sun, 31 Dec 2023 14:53:38 GMT
server: uvicorn
content-type: application/json                                 vary: Accept, Accept-Language, origin, Accept-Encoding
allow: GET, HEAD, OPTIONS
x-frame-options: SAMEORIGIN
x-api-version: 3
x-version: 1.17.4
content-length: 793
content-language: en-us                                        x-content-type-options: nosniff                                referrer-policy: same-origin
cross-origin-opener-policy: same-origin
```

**Comment by astubenbord** [comment]
Hm that's very weird. Maybe the /api/remote-version/ is only used for the auto update functionality, to indicate that a n new version is available? I think I'll switch to just reading the header.

**Comment by hermannoffen** [comment]
Just checked paperless‘ repo how the endpoint is implemented. See [permalink to implementation](https://github.com/paperless-ngx/paperless-ngx/blob/c754a5f391c41e2526e7151aafbf1c471ce3e35c/src/documents/views.py#L980).
Actually, it just checks GitHub for the latest tag and compares it with installed version. So, reading ˋx-versionˋ seems to be the way to go.

**Comment by astubenbord** [comment]
Right, I fixed it. Thanks for noticing!
