### ISSUE TITLE
[Bug]: preview empty for many documents

### ISSUE THREAD

**Issue by coro1404** [astubenbord/paperless-mobile#350]
### What happened?

Hi

latest paperless-ngx (2.3.0) - most documents do not have a preview (can view them as pdf after clicking the link). I have attached the logs. 

regards

### Steps to reproduce

1. Login to the app
2. click on document preview
3. no of pages etc. is displayed but preview stays empty

### Paperless-ng*x Version

2.3.1

### Paperless-Mobile Version

3.2.0+404

### Device

Google Pixel 8

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

German

### Additional Context

will attach file 
[paperless_mobile_logs_2024-01-07.log](https://github.com/astubenbord/paperless-mobile/files/13853764/paperless_mobile_logs_2024-01-07.log)

**Comment by langer70** [comment]
Habe das gleiche Problem.
Samsung Galaxy S10+

**Comment by coro1404** [comment]
adding a screenshot here 
![Screenshot_20240107-171247](https://github.com/astubenbord/paperless-mobile/assets/78205178/ec7cbcf0-8512-4bef-8172-1cfba7c7c54a)

**Comment by astubenbord** [comment]
Thanks, I can reproduce this. There seems to be an issue with the new version of the pdf library I'm using.
