### ISSUE TITLE
[Bug]: Exception: API 4 not supported

### ISSUE THREAD

**Issue by UlyssesZh** [astubenbord/paperless-mobile#355]
### What happened?

When I open the app, stuck at "Restoring session..."
![Screenshot_20240109-170829](https://github.com/astubenbord/paperless-mobile/assets/26196187/aae0fff7-0c0c-4b21-8537-a14fba8f4228)

### Steps to reproduce

Upgraded paperless-ngx, then this.

### Paperless-ng*x Version

2.3.2

### Paperless-Mobile Version

3.1.8

### Device

Samsung Galaxy S20

### Operating System Version

Android 11, One UI 3.1

### Device Locale

en-US

### Selected Locale

English (US)

**Comment by jdckr** [comment]
Duplicate #345

**Comment by UlyssesZh** [comment]
I see. Seems like the version on F-droid has not been updated yet.

**Comment by astubenbord** [comment]
Yeah, F-Droid tends to be slow in that regard. You can also use Obtanium or similar apps which allow to source app binaries directly from GitHub for instance.
