### ISSUE TITLE
[Bug]: cannot retrieve archive document from the overview tab

### ISSUE THREAD

**Issue by phlo2009** [astubenbord/paperless-mobile#361]
### What happened?

From Overview, tab the upper part of the screen does not show the archive document. 

### Steps to reproduce

1. Login sucessful. 
2. Tab to select a document from a provided list. 
3. Overview is automatically select by default. 
4. Tab on the partial document display on the top part of screen. 
5. A blank screen is displayed instead of full screen document data

### Paperless-ng*x Version

Paperless-ngx 2.3.3

### Paperless-Mobile Version

The latest from Google place store, ver 3.2

### Device

Google pixel 6

### Operating System Version

Android 14

### Device Locale

Canadian

### Selected Locale

None

**Comment by astubenbord** [comment]
Closing as duplicate of #350
