### ISSUE TITLE
[Bug]: PDF View is empty

### ISSUE THREAD

**Issue by andiant** [astubenbord/paperless-mobile#371]
### What happened?

Since the last Update, the PDF View is empty/blank. For any Document which I try to open. On the Web Version everything is still fine.

### Steps to reproduce

Just open any Document and tap on the preview to open the PDF View

### Paperless-ng*x Version

2.2.1

### Paperless-Mobile Version

3.2.0

### Device

Samsung Galaxy S23 Ultra

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

None

**Comment by andiant** [comment]
I have just seen that this bigreport is a duplicate of #366.
I think V3.2.0 should not be in playstore until this is fixed.

**Comment by astubenbord** [comment]
See status on #366. Closing as duplicate
