### ISSUE TITLE
Paperless ngx mit Home Assistant

### ISSUE THREAD

**Issue by andilix** [astubenbord/paperless-mobile#380]
Ich habe eine Installation von Paperless ngx als Addon von HomeAssistant eingerichtet und läuft auch alles soweit.

Jetzt wollte ich die Paperless  Mobile App benutzen.
Server angeben, Benutzername und Passwort eingeben klappt, beim nächsten Bildschirm steht dann Authentifizieren und es geht nichts mehr weiter.
Muss ich hierfür noch was spezielles irgendwo einstellen?

**Comment by astubenbord** [comment]
Hi, bitte nutze das Bug-Report Template und fülle die erforderlichen Informationen aus.

Vielen Dank

**Comment by donverse** [comment]
> Ich habe eine Installation von Paperless ngx als Addon von HomeAssistant eingerichtet und läuft auch alles soweit.
> 
> Jetzt wollte ich die Paperless Mobile App benutzen. Server angeben, Benutzername und Passwort eingeben klappt, beim nächsten Bildschirm steht dann Authentifizieren und es geht nichts mehr weiter. Muss ich hierfür noch was spezielles irgendwo einstellen?

bei mir funktioniert es mit ebendiesem setup problemlos

**Comment by astubenbord** [comment]
Closing in favor of #381
