### ISSUE TITLE
[Bug]: Dokument speichern funktioniert nicht 

### ISSUE THREAD

**Issue by Dibmi** [astubenbord/paperless-mobile#382]
### What happened?

Nach Änderung eines Dokumentes ist es nicht möglich diese Änderungen zu speichern. Das drücken des Änderungen speichern Buttons hat kein Auswirkung. 

### Steps to reproduce

Click Posteingang
Click Schnellaktion
Click Bearbeiten
Ändern von z. B Tags oder Korrespondenten
Änderungen speichern

### Paperless-ng*x Version

2.4.3

### Paperless-Mobile Version

3.2.1+405

### Device

Huawei P30pro

### Operating System Version

Android 12 EMUI

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment]
Closing as duplicate of #383

**Comment by Hant0r** [comment]
have the same problem.Device is the Pixel 8 Pro. 

It was marked as done, but how can I get the new sources on my device?
