### ISSUE TITLE
[Bug]: Login not possible in paperless-ngx with OIDC

### ISSUE THREAD

**Issue by Terminatorthre** [astubenbord/paperless-mobile#385]
### What happened?

Hi,
thanks for the great app. Not sure this is a bug or feature request actually.

I setup a brand new paperless-ngx instance that is connected to Keycloak as OIDC provider. It seems Paperless Mobile can not login to this instance and keeps spinning the wheel.

Support for OIDC Login would be awesome.

### Steps to reproduce

1. Try login with OIDC credentials in Paperless Mobile
2. Spinning wheel

### Paperless-ng*x Version

2.5.1

### Paperless-Mobile Version

3.2.1

### Device

Google Pixel 7

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

German

**Comment by Terminatorthre** [comment]
Just noticed there is a feature request for that already, sorry. #374

**Comment by ElCyborg** [comment]
A note, I just discovered this myself: 

If you setup an account first in paperless web, you can go and link it to a configured social provider (keycloak in my instance). This allows this app to log in with the native paperless account, and on web you can still use OIDC login flow.
