### ISSUE TITLE
[Bug]: Upload button disappears while keyboard is open

### ISSUE THREAD

**Issue by timomatrixer** [astubenbord/paperless-mobile#396]
### What happened?

Upload button disappears while keyboard is open. One mor Step needed (Return cmd of phone / swipe rigth to left), only then will the button be available again.

### Steps to reproduce

1. Scan Page with smartphone
2. Press upload button on the top
3. adjust the document settings (for example type in new title)
4. while keyboard is open scroll down to buttom -> No Upload Button 

### Screenshots

![Screenshot_20240307-063801](https://github.com/astubenbord/paperless-mobile/assets/40664333/8d837e5d-164c-43dc-b9c1-b7c008430e9e)
![Screenshot_20240307-063758](https://github.com/astubenbord/paperless-mobile/assets/40664333/40dc0b32-29e7-48df-b54b-020c70dd3293)

### Paperless-ng*x Version

2.5.4

### Paperless-Mobile Version

3.2.1+405

### Device

Pixel 7 Pro

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment]
I understand that this might be annoying on larger devices, where the button might easily fit above the keyboard and not hide any of the inputs. But on smaller devices, this is an issue and causes the user to not see some of the content.
