### ISSUE TITLE
[Bug]: Crop of pictures not accurate

### ISSUE THREAD

**Issue by timomatrixer** [astubenbord/paperless-mobile#397]
### What happened?

Crop of pictures not accurate. When making photos of documents, the automated crop function is less accurate. For Example the OneDrive App does this much better. 

The highest authority (my wife) has to be convinced here. :D

### Steps to reproduce

1. Scanner
2. Taking picture
3. See Crop Frame

### Screenshots

![Screenshot_20240307-063532](https://github.com/astubenbord/paperless-mobile/assets/40664333/5ad167c6-55b2-4dbe-8adc-6fbd8874197d)
![Screenshot_20240307-063552](https://github.com/astubenbord/paperless-mobile/assets/40664333/34be7dd6-d085-4da8-beeb-e0b5cd6384f4)

### Paperless-ng*x Version

2.5.4

### Paperless-Mobile Version

3.2.1+405

### Device

Pixel 7 Pro

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment]
Hi, this is an issue with the library I am using, I'll close this in favor of #322.
