### ISSUE TITLE
Document preview wrong

### ISSUE THREAD

**Issue by jdckr** [astubenbord/paperless-mobile#40]
When using the document preview not everything is shown. I normally add signatures to my documents by using PDFXChange Viewer. When viewing those documents in paperless-mobile, I can't see any text fields.
When sharing the pdf with another app to store it on the phone, everything is fine.

**Comment by astubenbord** [comment]
I'm using a simple pdf viewer library, I think it doesn't support additional features except preview. But I thought about using the syncfusion pdf viewer which is rich in features, I'm sure it would support it. It is also free for open source usage! I'll see what I can do when I find the time.

**Comment by astubenbord** [comment]
This is sort of implemented with the "Open in system viewer" action, so I'll close this as Paperless Mobile is not primarily a pdf viewer. Thanks.

**Comment by jdckr** [comment]
Already using it. Forgot about the issue already. Thanks a lot!
