### ISSUE TITLE
[Feature]: Login trough authentikator

### ISSUE THREAD

**Issue by PrzemekSkw** [astubenbord/paperless-mobile#405]
### Description

I set Authentik server and use it to get 2FA security layer for my Paperless server. It's not possible to login in app when there's Authentik login set first.
Regards.

**Comment by brilthor** [comment]
another browser based login feature: https://github.com/astubenbord/paperless-mobile/issues/387  Does paperless-mobile get a token from the API to use, or is everything auth'd with the un/pw?

**Comment by astubenbord** [comment]
I'll close this in favor of #374, this should be related, right? If not, feel free to reopen this issue.
