### ISSUE TITLE
[Improvement]: Edge detection performance is too low. 

### ISSUE THREAD

**Issue by mehmetalianil** [astubenbord/paperless-mobile#406]
### What happened?

I have scanned a few documents on different surfaces and lighting, edge detection never detected all vertices correctly, most of the cases detected one or two skewed, and 20% of the cases it detected edges of something in the document rather than the document edges. 

What I am more accustomed to is that edge detection works most of the time, but once in a while I have to adjust something. I am probably inadvertently comparing it with Google Drive scan feature. 

### Steps to reproduce

Take a photo of a document. 

### Paperless-ng*x Version

2.6.3

### Paperless-Mobile Version

3.2.1+405

### Device

Google Pixel 6

### Operating System Version

Android 14

### Device Locale

US

### Selected Locale

None

**Comment by astubenbord** [comment]
Yeah, I'll close this in favor of #322. The current scanner is not optimal since I just use an edge detection library. I'm planning on implementing it at some point but it's probably going to be far in the future.
