### ISSUE TITLE
Automatic ocr like on the website

### ISSUE THREAD

**Issue by languagemaniac** [astubenbord/paperless-mobile#448]
### Description

Hi, I mainly use paperless-ngx to scan tickets.

When I upload the pictures to the website it automatically performs ocr on them and this is very useful because it automatically assigns them a creation date, which matches the date on the ticket.

However on the app, when I scan a ticket, it asks me to fill in the creation date, which is ok but the website does that automatically so I was wondering if this feature could be added to the mobile version.

**Comment by kjabl** [comment]
Hi @languagemaniac ,
Just submit your document via the app without filling in the information. It will be uploaded and ocr and the usual stuff will be performed server side just like when uploading via the webapp.

**Comment by languagemaniac** [comment]
> Hi @languagemaniac ,
> Just submit your document via the app without filling in the information. It will be uploaded and ocr and the usual stuff will be performed server side just like when uploading via the webapp.

Oh ok didn't try that :') thanks
