### ISSUE TITLE
Preview of none pdf throws an error (seeddms) 

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#47]
The preview seems to work only for pdf documents. The preview of e.g. a jpg just issues an error msg.

**Comment by astubenbord** [comment]
That's weird, because as far as I know paperless always converts images into pdf format, see https://docs.paperless-ngx.com/faq/#what-file-types-does-paperless-ngx-support
Do you mean the document preview or the scanner preview?
What app version do you have installed and which server version are you running?

**Comment by steinm** [comment]
I ment the document preview, but you are right, paperless is supposed to return pdf in any case. Hence, there is no need to handle other formats than pdf. I'm actually not using a paperless server but seeddms (www.seeddms.org) which emulates the paperless api as good as possible. seeddms has no restrictions on file formats. It can store any file uploaded and if that file can be converted to pdf, it will convert it on request. There is no notion of an archived document. I initially thought, your app requests the original file on preview. Actually I wonder if there is a way to get back the original file, e.g. if it was a jpeg uploaded with 'paperless share'

**Comment by steinm** [comment]
BTW, if you want to try seeddms, just connect with your app to https://demo6.seeddms.org/restapi/index.php with admin/admin.

**Comment by astubenbord** [comment]
I see, I think this might be a good feature to support in the future. It should not be too much effort to check the mimetype of the file returned by document/:id/preview/ and open it in the system viewer.

**Comment by steinm** [comment]
I just realized that your app calls api/documents/{id}/download/ and api/documents/{id}/preview. Could that be the distinction to download the original file and the pdf version of it?

The title of this issue could be misleading. The native api of seeddms is quite different from the paperless api. I just added those api calls of paperless to make it work with your app, because it is a very efficient way to get documents into seeddms. Though it covers just a small portion of the functionality of seeddms.

**Comment by astubenbord** [comment]
As far as I know they are similar, both download and preview return a pdf file.

Right, I thought that the paperless api was natively built in, I'll change the title back.

**Comment by steinm** [comment]
I was looking for some more documentation at paperless ngx web site but quite find any. Do you have any more official information on what the different api calls precisly do? Maybe a swagger definition?

**Comment by astubenbord** [comment]
Unfortunately not, I also asked in the matrix chat, there should be a way to generate a swagger documentation from the Django framework but I couldn't manage to get it to run.

**Comment by astubenbord** [comment]
I'll maybe reconsider once the app has most of the paperless features implemented, until then, I'll probably not support other systems due to time constraints.
