### ISSUE TITLE
Saved views are not updated

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#51]
I often switch between two paperless ngx server. Both have saved views. Unfortunately, the app shows views from both servers no matter where I'm logged in. Looks like the app caches the list of saved views and doesn't refresh it after connecting to another server.

It also doesn't refresh the list of views after I have created a new one with the paperless ngx web gui client. Aren't views shared between clients?

**Comment by astubenbord** [comment]
Thanks for pointing that out, I forgot to implement the clean method of the repository. Should be fixed now.

**Comment by astubenbord** [comment]
Okay, I found the issue. I suppose you meant they were not loading when pulling down the refresh indicator on the "My Documents" page? Saved views should now reload in the upcoming release.

**Comment by steinm** [comment]
Refreshing the document list by pullling down the indicator is probably a good place to update the saved views.

BTW, the paperless web gui client and your app distinguishes between save views in the sidebar and on the dashboard. Does that have any meaning in your app?

**Comment by astubenbord** [comment]
That's how it is now implemented. 

No they don't and I don't intend to utilize these parameters in the future. I just want users to be able to configure the views so they works for both the web ui and this app. Maybe I should add a caption showing that they are not used in this app. I do however plan to make saved view creation more transparent and more encompassing, as there are far more parameters configurable than currently selectable in both the app and the web ui (see #11)

**Comment by astubenbord** [comment]
that's interesting, haven't thought about that. I'll have a look at the api once I have more time. Unfortunately, the documentation of the paperless API is not that detailed...

**Comment by astubenbord** [comment]
> Actually there is one thing I'm really missing (or I haven't found it yet). It's only partly related to saved views.
> 
> If you set the filter to 'Last 7 days' your app creates a query with a start date 8 days ago and an end date of tomorrow. If you save that as a view, it will save the dates. If you recall that view tomorrow or even next week it will not return the documents of the last 7 days, but the documents of 7 day period in the past.
> 
> The paperless web ui sets the query param to 'added:[-1 week to now]' instead.

Feel free to create a new issue from this, I'll close this one as it should be fixed in 1.3.1.

Cheers

**Comment by steinm** [comment]
I finally ended up with wireshark monitoring all the http traffic with the paperless server.

**Comment by astubenbord** [comment]
> I finally ended up with wireshark monitoring all the http traffic with the paperless server.

That's very creative 😄
