### ISSUE TITLE
Switching between documents and scanner resets filters and sorting

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#52]
Once you switch from the document list to the scanner or labels and than switch back, the filtering and sorting of the list is gone.

**Comment by astubenbord** [comment]
Yes, this is (currently) expected behavior, I will have to implement some sort of automatic persistence (I'm thinking about hydrated_bloc) of the document filter.

**Comment by astubenbord** [comment]
Implemented in [v1.4.1-beta](https://github.com/astubenbord/paperless-mobile/releases/tag/v1.4.1-beta).
