### ISSUE TITLE
Tags not selectable

### ISSUE THREAD

**Issue by Cat3006** [astubenbord/paperless-mobile#58]
Since the last Android App Update Tags are not selectable.
Click hits not the entry in the List, it hits the field of the form under it (for example "Korrespondent")

**Comment by astubenbord** [comment]
Hi, thanks for raising an issue.

Where exactly are you trying to select tags?
And I assume you are on version 1.4.1, is that correct?

**Comment by Cat3006** [comment]
App-Info Says 1.4.0.
Scanning Document, and then selecting already created Tag.

Issue also happening if editing Document, and then trying to select a tag

**Comment by astubenbord** [comment]
Yes, sorry, you're right, 1.4.0 is the latest version.
I just tried and it works on my phone. I'll have to investigate why this happens.

**Comment by Cat3006** [comment]
Happening on Galaxy Note 9. Android 10. Latest Updates installed

**Comment by astubenbord** [comment]
unfortunately I'm not able to reproduce the issue. Could you update to the latest version (now 1.4.1) and if the issue still persists make a screen recording of the bug?
