### ISSUE TITLE
File upload seems not to work on Pixel 6 Pro

### ISSUE THREAD

**Issue by ChristophCaina** [astubenbord/paperless-mobile#59]
Hi,
The file upload seems not to work on my Google Pixel 6 Pro.

Steps to reproduce:
- Open the App (I'm using biometrical authentication)
- On the Dashboard, default view is "Documents"...
  -> change to "scanner"
  - now, I can select:
    - scan a document -> which opens the camera (working)
    - **Upload a file from this device**
    The last one does not open a file browser in which I could select the corresponding file.

**Comment by astubenbord** [comment]
Hi, could this possibly be a permission issue? Could you try to re-install the app and see if a permission request pops up when pressing the button? Thanks

**Comment by ChristophCaina** [comment]
checking the permission information on the phone for the app, I can only see the camera.
Checking "all permissions" - I do have the following:

- Camera
Taking pictures and videos
- Others
Access all Networks
Use Biometrical Hardware
Access network connections
Use Fingerprint Hardware

I cannot see any other permission for File Storage or file broweser.

Uninstalling the app and installing it again did not change anything :-(
All settings (connection settings) were still available.
No Popup came up to ask for permissions.

**Comment by astubenbord** [comment]
Okay, I will add a check in the next version. On my phone it works without explicit permissions, maybe you can try the following (for now): Log out from the app. On the login screen, press "Select file" on the client certificate form field. This should ask you for permission to read from file storage. Select 'Allow" and continue as before. Could you tell me if this helps?

**Comment by ChristophCaina** [comment]
Logged out - tried to select the certificate.
Also, nothing happens. No file dialog, no request for permission.

Android OS: 13 (I can't find the exact build number atm)

**Comment by astubenbord** [comment]
Okay, then it seems the implicit permission was possibly changed with Android > 10. I will explicitly ask for permission in the next update.

**Comment by astubenbord** [comment]
Hi, the permissions were in fact changed with Android 13. However, I'm not sure if there is currently an existing solution in flutter. 

I'm going to have to wait for https://github.com/Baseflow/flutter-permission-handler/issues/907 to be merged/closed since this is the library I am using to handle permissions.

Also see https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by ChristophCaina** [comment]
That's OK. Isn't urgent :)

**Comment by astubenbord** [comment]
Never mind, good news: I have managed to fix it :) The issue was that I didn't have to ask for explicit permissions, it is apparently handled by the File picker itself. Should be fixed in the upcoming version.

**Comment by ChristophCaina** [comment]
Oh great :) 👍

**Comment by astubenbord** [comment]
Fixed in [v1.4.1-beta](https://github.com/astubenbord/paperless-mobile/releases/tag/v1.4.1-beta).
