### ISSUE TITLE
Edit button not visible, if document opened via Inbox

### ISSUE THREAD

**Issue by rsmuc** [astubenbord/paperless-mobile#61]
Edit button not visible, if document opened via Inbox

To reproduce:

- Open "Inbox / Posteingang"
- Open a document
--> Edit button is not available

If the same document is opened via the normal view, the Edit button is avialable.

Edit button not available:
![grafik](https://user-images.githubusercontent.com/6809635/211298428-fc8562a3-1e85-4767-a6c0-caae792f6baf.png)

Edit button available:
![grafik](https://user-images.githubusercontent.com/6809635/211298483-d25823f6-8411-45d8-bfde-ad221383ece9.png)

**Comment by astubenbord** [comment]
Hi, this is intended due to some previous architectural constraints. Should be possible now, I'll have a look.

**Comment by astubenbord** [comment]
Implemented in 1.5.0-beta
