### ISSUE TITLE
Support of "Suggestions"

### ISSUE THREAD

**Issue by rsmuc** [astubenbord/paperless-mobile#62]
Paperless-NGX supports "Suggestions" e.g. for alternative values for "Date created" that have been found in the document. Paperless-Mobile should support the suggestions:

![grafik](https://user-images.githubusercontent.com/6809635/211299326-f53f6357-7d99-4b53-9aca-454e8d2d4685.png)

**Comment by astubenbord** [comment]
Implemented in 1.5.0-beta

**Comment by steinm** [comment]
Is this what the restapi call /api/search/autocomplete/ does? https://github.com/bauerj/paperless_app has this feature when searching for documents. It list suggestions when type in a search term.

**Comment by astubenbord** [comment]
No, autocomplete is something different and is currently not implemented. Could you please create a feature request for this?

**Comment by steinm** [comment]
Thanks for the clarification. I found that feature in the documentation, but I could quite figure out how paperless ngx supplies this information. Can you give me a hint, e.g. a pointer to the paperless ngx source code?
