### ISSUE TITLE
Add support for autocompletion of search terms

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#67]
The rest api endpoint for autocompletion is /api/search/autocomplete/

See [source code](https://github.com/paperless-ngx/paperless-ngx/blob/4df065d8d524870ec18e8fbf2fc488449939a044/src-ui/src/app/services/rest/search.service.ts)

**Comment by astubenbord** [comment]
Implemented in [v1.5.1-beta](https://github.com/astubenbord/paperless-mobile/releases/tag/v1.5.1-beta)
