### ISSUE TITLE
More details in Inbox

### ISSUE THREAD

**Issue by rsmuc** [astubenbord/paperless-mobile#68]
The "mark as read" swipe function in the "Inbox" is very useful and speeds up the "review" workflow with Paperless.
But in the "Inbox" view the Correspondent and Document type is not visible. The matching of Paperless NGX is not 100% reliable, so I want to review the matching before removing it from the Inbox. 

So with the current implementation I open the "Inbox" of Paperless Mobile. Click the document to review the correct Correspondent and Type. If everything is OK I return to the "Inbox" and remove the document from the Inbox with the swipe-function. 

To process would be more efficient, if the Correspondent and Document type would be visible directly in the Inbox. Then I do not need to open the document etc. and could directly swipe the document away, when the matching was correct.

**Comment by astubenbord** [comment]
Implemented in v1.5.1-beta, hope you like it. If you have some more suggestions please let me know and I'll see what I can do!
