### ISSUE TITLE
Does not connect to my docker instance

### ISSUE THREAD

**Issue by stefanop1** [astubenbord/paperless-mobile#7]
Hello, thanks for your project that looks very promising.
I have a docker installation in my synology NAS. I don't use https connection but instead clear http. It is impossible to connect (Could not reach your Paperless server).

**Comment by astubenbord** [comment]
Hi, is your container running in host network mode or do you have it behind a proxy?

Can you connect to your instance via the paperless web server?

And what's the URL you're trying to connect to?

**Comment by stefanop1** [comment]
Yes, I can connect to the web interface. I have a public URL that points to my synology NAS.
I'm not sure if sending you the server address could expose me to attack. Can I have an email where to send the url? Or do you have an alternative for sending it? Thank you

**Comment by astubenbord** [comment]
@stefanop1 No worries, I don't need your exact address. 

The URL has to contain the scheme and your address (and optionally the port).  
So for instance: http://paperless.example.com or https://paperless.example.com:8000

If it doesn't work you could email me (mailto:anton.stubenbord@protonmail.com) your server address and then I can take a look whether I can connect.

**Comment by astubenbord** [comment]
@stefanop1 Should be fixed now (in 2f2312d5f36965604a5e9432582cb39cfa026d78). Could you try it out on your device?

**Comment by astubenbord** [comment]
Thanks! :) I guess it works now? Can I close the issue?
