### ISSUE TITLE
Can't upload documents scanned with the app

### ISSUE THREAD

**Issue by eikeja** [astubenbord/paperless-mobile#70]
When processing the file, there is an error under "File tasks": 'str' object has no attribute 'utcoffset'.

Pixel 7 Pro, Android 13
Newest App -Version
Paperless-Version: 1.11.3

**Comment by astubenbord** [comment]
Hi, this seems like it's a server side issue, see https://github.com/paperless-ngx/paperless-ngx/issues/2435

**Comment by shamoon** [comment]
The other way to handle this is to pass a valid iso 8601 string (technically thats what the api expects) but the linked change should make this more flexible anyway

**Comment by astubenbord** [comment]
@shamoon I already tried setting the 'created' field to '2023-01-16T23:57:02.563005Z', however, it results in the same error.

**Comment by shamoon** [comment]
Odd, ok well then im glad to have the change =)

**Comment by astubenbord** [comment]
Yeah, I'm starting to think that my paperless installation could be corrupt...

**Comment by astubenbord** [comment]
Hm, I just tried with a fresh local docker instance and it seems to work as expected, with both iso 8601 and yyyy-MM-dd formats...

**Comment by astubenbord** [comment]
@eikeja Is this resolved in the latest version?

**Comment by astubenbord** [comment]
Closing as duplicate of #72
