### ISSUE TITLE
New version crashes

### ISSUE THREAD

**Issue by WAdama** [astubenbord/paperless-mobile#71]
Hi,
the new version released a few days ago crashes on my tablet immediately after start.

Device: 
Samsung Galaxy Tab S8+
Android 13 
One UI 5.0
Kernel 5.10.81
App version 1.5.0

If there are any logs I could add, please let me know where to find them.

**Comment by astubenbord** [comment]
Hi, I also experienced this with android 13, the issue was related to https://github.com/flutter/flutter/issues/110658, I'll publish a fix today. Thanks for reporting!

**Comment by WAdama** [comment]
Then I'm wating for the fix and report.

Thanks!

**Comment by astubenbord** [comment]
Just published the update, should be out soon, please let me know if it crashes still. Just note that the app is not yet optimized for tablets, therefore some layouts might look weird.

**Comment by WAdama** [comment]
And I just tested the update: It works!

Thanks for your work, much appreciated...
