### ISSUE TITLE
Document date is wrong

### ISSUE THREAD

**Issue by codeflag** [astubenbord/paperless-mobile#75]
The issue date is displayed in the app with version 1.5.1 shifted by one day. However, everything is correct in the web application.

App:
![Screenshot_2023-01-19-20-10-21-57_d0490b14dafa2e72046a4566e3d7d027](https://user-images.githubusercontent.com/19187228/213538633-ca3a3d5b-797f-4cf2-9120-1cc8be15f26c.jpg)

Web application:
![Screenshot_2023-01-19-20-11-33-49_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/19187228/213538676-2958944b-37d7-4b45-b31d-528ee4ee574e.jpg)

**Comment by astubenbord** [comment]
Hi,  it was a UTC deserialization issue, will be fixed in next update.

**Comment by astubenbord** [comment]
Should be fixed in [v1.5.2-beta](https://github.com/astubenbord/paperless-mobile/releases/tag/v1.5.2-beta). Please let me know if it's still displayed wrongly!
