### ISSUE TITLE
Settings/application

### ISSUE THREAD

**Issue by stefanop1** [astubenbord/paperless-mobile#80]
When I select settings/application, only a white page is displayed. I try to uninstall but nothing change.
Thanks for this helpful app.

**Comment by astubenbord** [comment]
Hi, could you please provide the following information:
* App Version
* Device
* Android version

Thanks!

**Comment by stefanop1** [comment]
Samsung S22 ULTRA
App version 1.11.3 (API v2)
Android 13 One UI 5.0

**Comment by astubenbord** [comment]
Thanks, but the app version should be like 1.5.1, it is listed in the drawer when you click on  'about this app'. 1.11.3 is the paperless server version

**Comment by astubenbord** [comment]
Thanks for the update. I highly doubt that this is a server side issue because the settings are only local. Therefore this might have to do with the OS. I'll investigate bit I'm not sure I can solve this without debugging. Have you ever debugged/ran a flutter app? :)

**Comment by stefanop1** [comment]
Maybe the error is for y language? These are the first debug line when I choose settings/application:

ViewRootIm...nActivity] de.astubenbord.paperless_mobile      I  ViewPostIme pointer 0
ViewRootIm...nActivity] de.astubenbord.paperless_mobile      I  ViewPostIme pointer 1
flutter                 de.astubenbord.paperless_mobile      I  Null check operator used on a null value
flutter                 de.astubenbord.paperless_mobile      I  #0      _LanguageSelectionSettingState.build.<anonymous closure> (package:paperless_mobile/features/settings/view/widgets/language_selection_setting.dart:29)
flutter                 de.astubenbord.paperless_mobile      I  #1      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:90)
flutter                 de.astubenbord.paperless_mobile      I  #2      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:166)
flutter                 de.astubenbord.paperless_mobile      I  #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5107)
flutter                 de.astubenbord.paperless_mobile      I  #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4995)

Thanks, Stefano

**Comment by astubenbord** [comment]
May I ask what your system language is? Thanks!

**Comment by stefanop1** [comment]
My system language is 'it' Thanks. I'll try with a different language. Maybe switching helps

**Comment by stefanop1** [comment]
Setting English/US doesn't help :(

**Comment by astubenbord** [comment]
Ah, I see! That explains it. As a quick fix, you can try to uninstall the app, change your system language to english and reinstall the app. The problem is that he app currently automatically sets your preferred language to your system language. If no translations exist, an error will occur. I'll fix this in the upcoming update. Until then, the workaround should do. You can also set your system language to it again after having logged back in.

**Comment by astubenbord** [comment]
Does it work without the workaround in the newest version?
