### ISSUE TITLE
[BUG] App is using 60hz on a high refresh rate device

### ISSUE THREAD

**Issue by lagmoellertim** [astubenbord/paperless-mobile#85]
**Describe the bug**
The App is rendering in 60hz, even though the screen supports 90hz

**To Reproduce**
1. Open the app on a high refresh screen

**Expected behavior**
The app should render using the maximum available refresh rate of the device

**Device Information:**
 - Device: OnePlus Nord 2
 - OS: Android 13
 - Paperless Mobile version 1.5.3+16
 - Paperless Server version 1.11.3

**Additional context**
I also looked into flutter development a while ago and I experienced the same issue, so it's more a flutter problem than a fault of your app. Either way, it would be great if this could be fixed, since in comparison to other apps this one feels "stuttery". This may be a OnePlus specific problem. Back then, I fixed it using this [library](https://pub.dev/packages/flutter_displaymode).

**Comment by astubenbord** [comment]
Hi, thanks for raising an issue. The app still has beta status, therefore the code has not yet been optimized much. Also, I've heard that flutter 3.7 introduced quite some performance improvements, maybe this will also help to make it more smooth. As far as I know flutter always tries to render in 60Hz. I'll keep this in mind but I don't think that I'll get to this very soon considering the upcoming paperless update with multi user support, which will be quite some work for me aswell. I'll put this in the backlog, but feel free to open a pull request!
