### ISSUE TITLE
[BUG] Not able to select correspondent or document type

### ISSUE THREAD

**Issue by ChamesBont** [astubenbord/paperless-mobile#88]
**Describe the bug**
If I try to select a correspondent from the popup list i select the field in the background (document type).
That only happens with the last entry in the list or if only one entry is left.

**To Reproduce**
1. Go to 'Edit document'
2. Click on 'correspondent for example'
3. The selector jumps into the "document type" field which is in the background of the correspondent selector

**Expected behavior**
If i tap on the correspondents name it should select it instead select the field in the background.

**Device Information:**
 - Device: Google Pixel 7
 - OS: Android 12
 - Paperless Mobile version 1.5.3
 - Paperless Server version 1.12.1

**Comment by astubenbord** [comment]
Hi, we had a discussion yesterday in #83 about this exact issue. Please have a look and try to disable accessibility features of bitwarden of similar apps.

Unfortunately this is a bug with either Android or the framework, so there's not much I can do. Thanks.
