### ISSUE TITLE
Notification 'You are offline' on top of screen

### ISSUE THREAD

**Issue by stefanop1** [astubenbord/paperless-mobile#9]
Although it appears that I am connected correctly there is a notification on top of screen (You're offline. Check your connection).
I use Synology's reverse proxy

**Comment by astubenbord** [comment]
Hi, this means that you're neither connected via wifi nor mobile data. Is this the case?

**Comment by stefanop1** [comment]
I am connected. The app working OK but I have this notification on top of screen. This appears on WI-FI and mobile data.
I suspect that is only a cosmetic issue

**Comment by astubenbord** [comment]
What android version are you using and what phone model?

**Comment by stefanop1** [comment]
I'm using Android 13 with Samsung S22 ultra.
Strange. now the notification is gone. Please close this bug. I keep you informed.

**Comment by astubenbord** [comment]
Feel free to test the new release v1.0.3-beta, I made some changes to connectivity.

**Comment by stefanop1** [comment]
With version 1.0.3, off-line reporting no longer occurred. You can close the issue. Thank you
