### ISSUE TITLE
Use same type of view in saved views as on document tab

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#93]
I usually display documents as tiles (preview image on the top and some meta data under it) and not in a list (preview image on the left and meta data right to it). Unfortunately, the saved views always start with a list view. Wouldn't it be better to take over the same type of view used on the documents tab?

**Comment by astubenbord** [comment]
I see your point. However, I would not synchronize them as, at least in my opinion, they are separate concerns. I have two proposals for you:

1. I could use the stored view type from the main documents view as the default for the saved views but keep them independent, i.e. changing the view type in the saved views will not affect the stored setting for the main documents view
2. Store the view type separately for saved views (in your case you'd have to set it once and then never again.)

What would you prefer? Or is there any reason you think they should be synchronized?

**Comment by steinm** [comment]
You are right, synchronizing is not the right way to go. I was just my first thought while lacking for alternatives. Your first proposal sounds reasonable, if the view type can be saved with a stored view. The web gui of paperless-ngx appears to *not* save the view type within a saved view.

**Comment by astubenbord** [comment]
I meant to save the view type in the saved views screen separately, just like I save the view type for the documents view, so not with a saved view itself but rather the screen.

**Comment by steinm** [comment]
Sounds like a good solution.

**Comment by astubenbord** [comment]
Implemented in v2.0.4
