### ISSUE TITLE
Question: Build instructions

### ISSUE THREAD

**Issue by iulica** [astubenbord/paperless-mobile#95]
As I was trying to fix the downloads issue, I followed your instructions to the letter and couldn't get it running with the following error:
packages/paperless_api/lib/src/models/labels/correspondent_model.dart:6:6: Error: Error when reading 'packages/paperless_api/lib/src/models/labels/correspondent_model.g.dart': No such file or directory
part 'correspondent_model.g.dart';
     ^
After digging it, I realised that the 
flutter packages pub run build_runner build --delete-conflicting-outputs
didn't ran inside the packages folder. 

My solution is to go to the packages/paperless_api folder and run the steps 2,3 and 4 there as well.
I may have missed something but if this is the proper way to do it, then it would be helpful to mention it in the documentation as well.

Thanks

**Comment by astubenbord** [comment]
Hi, you're right, I'll add these steps to the readme!
